<?php
$plans=[
 ['name'=>'Day Pass','price'=>'₦5,000','note'=>'Walk-in access','items'=>['Full-day gym floor access','Cardio, weights and stretch zone','Locker support','Good for first-time visitors']],
 ['name'=>'Monthly Grind','price'=>'₦25,000','note'=>'Most popular','hot'=>true,'items'=>['Unlimited monthly access','Group classes included','Progress check-in','Renewal reminder before expiry']],
 ['name'=>'Quarterly Beast','price'=>'₦85,000','note'=>'Consistency plan','items'=>['3 months full access','Priority class booking','Monthly body review','Member support on WhatsApp']],
 ['name'=>'Annual Elite','price'=>'₦340,000','note'=>'Best value','items'=>['12 months full access','VIP member support','Quarterly assessments','Exclusive shop offers']],
];
$classes=[
 ['day'=>'MON','time'=>'7:30 AM','name'=>'Strength Lab','coach'=>'Coach Daniel','level'=>'All levels'],
 ['day'=>'TUE','time'=>'8:00 AM','name'=>'Core Burn','coach'=>'Coach Femi','level'=>'Intermediate'],
 ['day'=>'WED','time'=>'5:00 PM','name'=>'Mobility Reset','coach'=>'Coach Amara','level'=>'Beginner friendly'],
 ['day'=>'THU','time'=>'6:00 PM','name'=>'Boxing Fit','coach'=>'Coach Femi','level'=>'High energy'],
 ['day'=>'FRI','time'=>'5:30 PM','name'=>'Afro Dance Cardio','coach'=>'Coach Amara','level'=>'All levels'],
 ['day'=>'SAT','time'=>'9:00 AM','name'=>'Weekend Sweat','coach'=>'Smart Gym Team','level'=>'Group session']
];
$programs=[
 ['num'=>'01','title'=>'Gym Memberships','text'=>'Daily, monthly, quarterly and annual access for different budgets and fitness goals.','img'=>'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80'],
 ['num'=>'02','title'=>'Personal Training','text'=>'One-on-one coaching for weight loss, muscle gain, endurance and body transformation.','img'=>'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=900&q=80'],
 ['num'=>'03','title'=>'Online Coaching','text'=>'Remote training guidance, accountability check-ins, nutrition direction and flexible routines.','img'=>'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80'],
 ['num'=>'04','title'=>'Group Classes','text'=>'Strength, cardio, mobility, boxing, dance fitness and weekend sweat sessions.','img'=>'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=80'],
 ['num'=>'05','title'=>'Gym Shop','text'=>'Supplements, gloves, resistance bands, gym wear, shakers and fitness accessories.','img'=>'https://images.unsplash.com/photo-1599058917765-a780eda07a3e?auto=format&fit=crop&w=900&q=80']
];
$shop=[['item'=>'Whey Protein','price'=>'From ₦38,000'],['item'=>'Pre-workout','price'=>'From ₦22,000'],['item'=>'Gym Gloves','price'=>'From ₦8,500'],['item'=>'Resistance Bands','price'=>'From ₦6,000']];
$testimonials=[['name'=>'Tosin A.','text'=>'I joined for weight loss but stayed because the coaches actually follow up.'],['name'=>'Chika M.','text'=>'The monthly plan and evening classes fit perfectly into my work schedule.'],['name'=>'Ifeanyi K.','text'=>'Boxing Fit changed my stamina. The environment feels serious but friendly.']];
$gallery=['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1000&q=80','https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1000&q=80','https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1000&q=80','https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1000&q=80'];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Smart Gym | Modern Fitness Club & Training Studio</title><meta name="description" content="Smart Gym is a bold fitness club for memberships, personal training, group classes, boxing fitness, online coaching and gym product enquiries."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/styles.css?v=smartgym-complete-20260911"></head><body>
<div class="demo-strip">DEMO PREVIEW · Smart Gym sample website by LynxCom Analytics</div>
<header class="sg-header"><a class="sg-logo" href="#top"><span>SG</span><b>SMART GYM</b></a><nav><a href="#memberships">Membership</a><a href="#programs">Programs</a><a href="#schedule">Schedule</a><a href="#coaches">Coaches</a><a href="#join">Join</a></nav><a class="header-btn" href="#join">Start Now</a></header>
<main id="top"><section class="hero-stage hero-photo"><div class="hero-left"><p class="mini">Fitness club · coaching · classes · transformation</p><h1>Build strength. Burn limits. Train smarter.</h1><p class="hero-text">A high-energy gym experience for people who want structure, coaching, community and visible progress — from daily access to personal training and online coaching.</p><div class="hero-actions"><a href="#memberships" class="btn fire">View Plans</a><a href="#join" class="btn ghost">Register Interest</a></div></div><div class="hero-right"><figure class="main-photo"><img src="https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1100&q=80" alt="Smart Gym strength training area"><figcaption>Modern strength and cardio training floor</figcaption></figure><div class="metric-card top"><b>248</b><span>Active Members</span></div><div class="metric-card bottom"><b>312</b><span>Sessions Booked</span></div></div></section>
<section class="quick-book"><div><b>Open Mon–Sat</b><span>7:00AM – 7:00PM</span></div><div><b>Location</b><span>Sample City, Nigeria</span></div><div><b>WhatsApp</b><span>+234 800 000 0000</span></div><a href="#join">Book a Tour →</a></section>
<section class="about-block image-about"><div class="vertical-title">SMART<br>FITNESS</div><div><span class="label">Not just a gym</span><h2>A fitness community built for training, accountability and better habits.</h2></div><div><p>Smart Gym supports beginners, busy professionals, students and fitness lovers with flexible membership plans, guided routines, personal coaching, boxing fitness, wellness classes and online support.</p><div class="mini-stats"><span><b>6</b> Weekly Classes</span><span><b>3</b> Coaches</span><span><b>4</b> Membership Plans</span></div></div></section>
<section class="program-wall" id="programs"><?php foreach($programs as $p): ?><article class="program-photo"><img src="<?=$p['img']?>" alt="<?=$p['title']?> at Smart Gym"><span><?=$p['num']?></span><h3><?=$p['title']?></h3><p><?=$p['text']?></p></article><?php endforeach; ?></section>
<section class="membership-section" id="memberships"><div class="section-title"><span>Membership</span><h2>Choose your training lane.</h2></div><div class="membership-grid"><?php foreach($plans as $p): ?><article class="membership-card <?=!empty($p['hot'])?'hot':''?>"><small><?=$p['note']?></small><h3><?=$p['name']?></h3><div class="amount"><?=$p['price']?></div><ul><?php foreach($p['items'] as $item): ?><li><?=$item?></li><?php endforeach; ?></ul><a href="#join">Select plan</a></article><?php endforeach; ?></div></section>
<section class="gallery-section"><div class="section-title"><span>Gym environment</span><h2>Sample image gallery.</h2></div><div class="gallery-grid"><?php foreach($gallery as $i=>$img): ?><figure><img src="<?=$img?>" alt="Smart Gym sample gallery image <?=($i+1)?>"><figcaption><?=['Training floor','Personal coaching','Strength equipment','Conditioning session'][$i]?></figcaption></figure><?php endforeach; ?></div></section>
<section class="transformation"><div><span class="label">Transformation focus</span><h2>From first visit to measurable progress.</h2><p>The final client system can collect registrations, attendance, subscription renewals, personal training demand, class interest and product enquiries for easy LynxCom dashboards.</p></div><div class="progress-board"><div><span>New members</span><b>+42</b></div><div><span>Renewals due</span><b>18</b></div><div><span>Class bookings</span><b>76</b></div><div><span>Follow-ups</span><b>11</b></div></div></section>
<section class="schedule" id="schedule"><div class="section-title"><span>Weekly energy</span><h2>Sample class schedule.</h2></div><div class="schedule-list"><?php foreach($classes as $c): ?><article><b><?=$c['day']?></b><div><h3><?=$c['name']?></h3><span><?=$c['time']?> · <?=$c['coach']?> · <?=$c['level']?></span></div><a href="#join">Join</a></article><?php endforeach; ?></div></section>
<section class="shop-section"><div class="section-title"><span>Gym shop</span><h2>Sample products members can request.</h2></div><div class="shop-grid"><?php foreach($shop as $s): ?><article><h3><?=$s['item']?></h3><p><?=$s['price']?></p><a href="#join">Ask availability</a></article><?php endforeach; ?></div></section>
<section class="coaches" id="coaches"><div class="section-title"><span>Coaches</span><h2>Meet the team driving the results.</h2></div><div class="coach-grid"><article><div>D</div><h3>Coach Daniel</h3><p>Strength, conditioning and beginner gym confidence.</p></article><article><div>A</div><h3>Coach Amara</h3><p>Mobility, wellness, dance fitness and recovery.</p></article><article><div>F</div><h3>Coach Femi</h3><p>Boxing fitness, HIIT and endurance conditioning.</p></article></div></section>
<section class="testimonial-section"><div class="section-title"><span>Member stories</span><h2>Sample testimonials.</h2></div><div class="testimonial-grid"><?php foreach($testimonials as $t): ?><article><p>“<?=$t['text']?>”</p><b><?=$t['name']?></b></article><?php endforeach; ?></div></section>
<section class="join-section" id="join"><div class="join-copy"><span class="label">Join Smart Gym</span><h2>Register interest. Let the team contact you.</h2><p>This demo form shows the data collection pipeline: every enquiry can become a clean member record for dashboards, follow-up and subscription tracking.</p><ul><li>Membership enquiry captured</li><li>Plan preference recorded</li><li>Fitness goal stored</li><li>Follow-up list ready for the gym team</li></ul></div><form class="join-form" method="post" action="submit-member.php"><input name="name" required placeholder="Full name"><input name="phone" required placeholder="Phone / WhatsApp"><input type="email" name="email" placeholder="Email address"><select name="plan"><option>Monthly Grind</option><option>Day Pass</option><option>Quarterly Beast</option><option>Annual Elite</option><option>Personal Training</option><option>Online Coaching</option><option>Gym Shop Enquiry</option></select><textarea name="goal" placeholder="What is your fitness goal or enquiry?"></textarea><button>Submit Registration</button></form></section></main><footer class="sg-footer"><b>SMART GYM</b><span>Fitness website + data collection demo by LynxCom Analytics</span></footer><script src="assets/script.js?v=smartgym-complete-20260911"></script></body></html>
