<?php

function smart_gym_csv_count($file){
  if(!file_exists($file)) return 0;
  $rows = file($file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
  return max(0, count($rows)-1);
}
$memberSubmissions = smart_gym_csv_count(__DIR__.'/data/member-registrations.csv');
$launchDate = new DateTime('2026-09-11');
$today = new DateTime('today');
$daysLive = max(0, (int)$launchDate->diff($today)->format('%r%a'));
$metrics=[
 ['key'=>'members','label'=>'New members','value'=>42 + ($daysLive * 3) + $memberSubmissions,'delta'=>'+'.(6+$memberSubmissions).' this week','detail'=>'Counts new member enquiries and registrations captured through the website form. In production this can sync from walk-ins, WhatsApp enquiries and front-desk entries.'],
 ['key'=>'renewals','label'=>'Renewals due','value'=>18 + ($daysLive % 5),'delta'=>'Next 7 days','detail'=>'Shows members whose subscriptions are close to expiry, helping the gym follow up before revenue is lost.'],
 ['key'=>'classes','label'=>'Class bookings','value'=>76 + ($daysLive * 4) + min(12,$memberSubmissions),'delta'=>'Across 6 classes','detail'=>'Tracks class interest/bookings for strength, boxing, cardio, mobility and weekend sessions.'],
 ['key'=>'followups','label'=>'Follow-ups','value'=>11 + $memberSubmissions,'delta'=>'Action list','detail'=>'Shows prospects or members the gym team should call, message or convert into paid plans.'],
];
$metricByKey=[]; foreach($metrics as $m){ $metricByKey[$m['key']]=$m; }
$plans=[
 ['name'=>'Day Pass','price'=>'₦5,000','note'=>'Walk-in access','items'=>['Full-day gym floor access','Cardio, weights and stretch zone','Locker support','Good for first-time visitors']],
 ['name'=>'Monthly Grind','price'=>'₦25,000','note'=>'Most popular','hot'=>true,'items'=>['Unlimited monthly access','Group classes included','Progress check-in','Renewal reminder before expiry']],
 ['name'=>'Quarterly Beast','price'=>'₦85,000','note'=>'Consistency plan','items'=>['3 months full access','Priority class booking','Monthly body review','Member support on WhatsApp']],
 ['name'=>'Annual Elite','price'=>'₦340,000','note'=>'Best value','items'=>['12 months full access','VIP member support','Quarterly assessments','Exclusive shop offers']],
];
$classes=[
 ['day'=>'MON','time'=>'7:30 AM','name'=>'Strength Lab','coach'=>'Coach Daniel','level'=>'All levels'],
 ['day'=>'TUE','time'=>'8:00 AM','name'=>'Core Burn','coach'=>'Coach Femi','level'=>'Intermediate'],
 ['day'=>'WED','time'=>'5:00 PM','name'=>'Mobility Reset','coach'=>'Coach Amara','level'=>'Beginner friendly'],
 ['day'=>'THU','time'=>'6:00 PM','name'=>'Boxing Fit','coach'=>'Coach Femi','level'=>'High energy'],
 ['day'=>'FRI','time'=>'5:30 PM','name'=>'Afro Dance Cardio','coach'=>'Coach Amara','level'=>'All levels'],
 ['day'=>'SAT','time'=>'9:00 AM','name'=>'Weekend Sweat','coach'=>'Smart Shape Fitness Gym Team','level'=>'Group session']
];
$programs=[
 ['num'=>'01','title'=>'Gym Memberships','text'=>'Daily, monthly, quarterly and annual access for different budgets and fitness goals.','img'=>'assets/img/membership-naija-v2-20260911.webp'],
 ['num'=>'02','title'=>'Personal Training','text'=>'One-on-one coaching for weight loss, muscle gain, endurance and body transformation.','img'=>'assets/img/personal-training-naija-v2-20260911.webp'],
 ['num'=>'03','title'=>'Online Coaching','text'=>'Remote training guidance, accountability check-ins, nutrition direction and flexible routines.','img'=>'assets/img/online-coaching-naija-v2-20260911.webp'],
 ['num'=>'04','title'=>'Group Classes','text'=>'Strength, cardio, mobility, boxing, dance fitness and weekend sweat sessions.','img'=>'assets/img/classes-naija-v2-20260911.webp'],
 ['num'=>'05','title'=>'Gym Shop','text'=>'Supplements, gloves, resistance bands, gym wear, shakers and fitness accessories.','img'=>'assets/img/shop-naija-v2-20260911.webp']
];
$shop=[['item'=>'Whey Protein','price'=>'From ₦38,000','img'=>'assets/img/products/whey-protein-20260911.webp'],['item'=>'Pre-workout','price'=>'From ₦22,000','img'=>'assets/img/products/pre-workout-20260911.webp'],['item'=>'Gym Gloves','price'=>'From ₦8,500','img'=>'assets/img/products/gym-gloves-20260911.webp'],['item'=>'Resistance Bands','price'=>'From ₦6,000','img'=>'assets/img/products/resistance-bands-20260911.webp']];
$testimonials=[['name'=>'Tosin A.','text'=>'I joined for weight loss but stayed because the coaches actually follow up.'],['name'=>'Chika M.','text'=>'The monthly plan and evening classes fit perfectly into my work schedule.'],['name'=>'Ifeanyi K.','text'=>'Boxing Fit changed my stamina. The environment feels serious but friendly.']];
$gallery=['assets/img/gallery-floor-naija-v2-20260911.webp','assets/img/gallery-coaching-naija-v2-20260911.webp','assets/img/gallery-strength-naija-v2-20260911.webp','assets/img/gallery-conditioning-naija-v2-20260911.webp'];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Smart Shape Fitness Gym | Modern Fitness Club & Training Studio</title><meta name="description" content="Smart Shape Fitness Gym is a bold fitness club for memberships, personal training, group classes, boxing fitness, online coaching and gym product enquiries."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/styles.css?v=smartshape-card-fit-20260912"></head><body>
<header class="sg-header"><a class="sg-logo" href="#top"><img class="brand-logo" src="assets/img/smart-shape-professional-logo.jpg" alt="Smart Shape Fitness Gym professional logo"><b>SMART SHAPE</b></a><button class="mobile-menu-toggle" type="button" aria-expanded="false" aria-controls="site-menu">Menu</button><nav id="site-menu"><a href="#top">Home</a><a href="#memberships">Membership Plans</a><a href="#programs">Programs</a><a href="#schedule">Schedule</a><a href="shop.php">Shop</a><a href="#coaches">Trainers</a><a href="#join">Join</a></nav><a class="header-btn" href="#join">Start Now</a></header>
<main id="top"><section class="hero-stage hero-photo"><div class="hero-left"><p class="mini">Fitness club · coaching · classes · transformation</p><h1>Build strength. Burn limits. Train smarter.</h1><p class="hero-text">A high-energy gym experience for people who want structure, coaching, community and visible progress — from daily access to personal training and online coaching.</p><div class="hero-actions"><a href="#memberships" class="btn fire">View Plans</a><a href="#join" class="btn ghost">Register Interest</a></div></div><div class="hero-right"><figure class="main-photo"><img src="assets/img/hero-naija-v2-20260911.webp" alt="Black Nigerian members training at Smart Shape Fitness Gym" width="900" height="614" loading="eager" decoding="async" fetchpriority="high"><figcaption>Modern strength and cardio training floor</figcaption></figure><div class="metric-card top"><b><?=number_format($metricByKey['members']['value']+206)?></b><span>Active Members</span></div><div class="metric-card bottom"><b><?=number_format($metricByKey['classes']['value']+236)?></b><span>Sessions Booked</span></div></div></section>
<section class="quick-book"><div><b>Open Mon–Sat</b><span>7:00AM – 7:00PM</span></div><div><b>Location</b><span>Nigeria</span></div><div><b>WhatsApp</b><span>+234 800 000 0000</span></div><a href="#join">Book a Tour →</a></section>
<section class="about-block image-about"><div class="vertical-title">SMART<br>FITNESS</div><div><span class="label">Not just a gym</span><h2>A fitness community built for training, accountability and better habits.</h2></div><div><p>Smart Shape Fitness Gym supports beginners, busy professionals, students and fitness lovers with flexible membership plans, guided routines, personal coaching, boxing fitness, wellness classes and online support.</p><div class="mini-stats"><span><b>6</b> Weekly Classes</span><span><b>3</b> Coaches</span><span><b>4</b> Membership Plans</span></div></div></section>
<section class="program-wall" id="programs"><?php foreach($programs as $p): ?><article class="program-photo"><img src="<?=$p['img']?>" alt="<?=$p['title']?> with Black Nigerian gym members at Smart Shape Fitness Gym" loading="lazy" decoding="async"><span><?=$p['num']?></span><h3><?=$p['title']?></h3><p><?=$p['text']?></p></article><?php endforeach; ?></section>
<section class="membership-section" id="memberships"><div class="section-title"><span>Membership</span><h2>Choose your training lane.</h2></div><div class="membership-grid"><?php foreach($plans as $p): ?><article class="membership-card <?=!empty($p['hot'])?'hot':''?>"><small><?=$p['note']?></small><h3><?=$p['name']?></h3><div class="amount"><?=$p['price']?></div><ul><?php foreach($p['items'] as $item): ?><li><?=$item?></li><?php endforeach; ?></ul><a href="#join">Select plan</a></article><?php endforeach; ?></div></section>
<section class="gallery-section"><div class="section-title"><span>Gym environment</span><h2>Image gallery.</h2></div><div class="gallery-grid"><?php foreach($gallery as $i=>$img): ?><figure><img src="<?=$img?>" alt="Black Nigerian Smart Shape Fitness Gym gallery image <?=($i+1)?>" loading="lazy" decoding="async"><figcaption><?=['Training floor','Personal coaching','Strength equipment','Conditioning session'][$i]?></figcaption></figure><?php endforeach; ?></div></section>
<section class="transformation"><div><span class="label">Transformation focus</span><h2>From first visit to measurable progress.</h2><p>Track your training journey from first visit to consistent progress with membership support, class interest, coaching guidance and follow-up.</p></div><div class="progress-board dynamic-metrics"><?php foreach($metrics as $m): ?><button type="button" class="metric-tile" data-label="<?=htmlspecialchars($m['label'])?>" data-value="<?=number_format($m['value'])?>" data-detail="<?=htmlspecialchars($m['detail'])?>"><span><?=$m['label']?></span><b><?=($m['key']==='members'?'+':'')?><?=number_format($m['value'])?></b><small><?=$m['delta']?></small></button><?php endforeach; ?></div></section>
<section class="schedule" id="schedule"><div class="section-title"><span>Weekly energy</span><h2>Class schedule.</h2></div><div class="schedule-list"><?php foreach($classes as $c): ?><article><b><?=$c['day']?></b><div><h3><?=$c['name']?></h3><span><?=$c['time']?> · <?=$c['coach']?> · <?=$c['level']?></span></div><a href="#join">Join</a></article><?php endforeach; ?></div></section>
<section class="shop-section" id="shop"><div class="section-title"><span>Gym shop</span><h2>Products members can request.</h2><a class="section-more" href="shop.php">Shop More →</a></div><div class="shop-grid"><?php foreach($shop as $s): ?><article><img class="product-thumb" src="<?=$s['img']?>" alt="<?=$s['item']?> at Smart Shape Fitness Gym shop" loading="lazy" decoding="async"><h3><?=$s['item']?></h3><p><?=$s['price']?></p><a href="shop.php">View in shop</a></article><?php endforeach; ?></div></section>
<section class="coaches" id="coaches"><div class="section-title"><span>Coaches</span><h2>Meet the team driving the results.</h2></div><div class="coach-grid"><article><div class="coach-avatar"><img src="assets/img/coach-daniel-naija-20260911.webp" alt="Coach Daniel, Black Nigerian Smart Shape Fitness Gym strength coach" loading="lazy" decoding="async"></div><h3>Coach Daniel</h3><p>Strength, conditioning and beginner gym confidence.</p></article><article><div class="coach-avatar"><img src="assets/img/coach-amara-naija-20260911.webp" alt="Coach Amara, Black Nigerian Smart Shape Fitness Gym wellness coach" loading="lazy" decoding="async"></div><h3>Coach Amara</h3><p>Mobility, wellness, dance fitness and recovery.</p></article><article><div class="coach-avatar"><img src="assets/img/coach-femi-naija-20260911.webp" alt="Coach Femi, Black Nigerian Smart Shape Fitness Gym boxing fitness coach" loading="lazy" decoding="async"></div><h3>Coach Femi</h3><p>Boxing fitness, HIIT and endurance conditioning.</p></article></div></section>
<section class="testimonial-section"><div class="section-title"><span>Member stories</span><h2>Member testimonials.</h2></div><div class="testimonial-grid"><?php foreach($testimonials as $t): ?><article><p>“<?=$t['text']?>”</p><b><?=$t['name']?></b></article><?php endforeach; ?></div></section>
<section class="join-section" id="join"><div class="join-copy"><span class="label">Join Smart Shape Fitness Gym</span><h2>Register interest. Let the team contact you.</h2><p>Send your details and the Smart Shape Fitness Gym team will contact you about membership, coaching, classes or product enquiries.</p><ul><li>Membership enquiry captured</li><li>Plan preference recorded</li><li>Fitness goal stored</li><li>Follow-up list ready for the gym team</li></ul></div><form class="join-form" method="post" action="submit-member.php"><input name="name" required placeholder="Full name"><input name="phone" required placeholder="Phone / WhatsApp"><input type="email" name="email" placeholder="Email address"><select name="plan"><option>Monthly Grind</option><option>Day Pass</option><option>Quarterly Beast</option><option>Annual Elite</option><option>Personal Training</option><option>Online Coaching</option><option>Gym Shop Enquiry</option></select><textarea name="goal" placeholder="What is your fitness goal or enquiry?"></textarea><button>Submit Registration</button></form></section></main><footer class="sg-footer"><b>SMART SHAPE</b><span>Smart Shape Fitness Gym · Train stronger. Shape better. Stay consistent.</span></footer><script src="assets/script.js?v=smartshape-card-fit-20260912"></script></body></html>
