<?php
$brand = 'Smart Gym';
$phone = '+234 800 000 0000';
$email = 'hello@smartgym.com';
$plans = [
  ['name'=>'Day Pass','price'=>'₦5,000','tag'=>'Flexible access','items'=>['Full gym access for one day','Cardio and weights floor','Locker access','Perfect for walk-ins']],
  ['name'=>'Two-Week Reset','price'=>'₦20,000','tag'=>'Short commitment','items'=>['14 days gym access','Fitness assessment','Group class access','Progress check-in']],
  ['name'=>'Monthly Active','price'=>'₦25,000','tag'=>'Most popular','featured'=>true,'items'=>['One month unlimited gym access','Group classes included','Trainer support on floor','Member progress tracking']],
  ['name'=>'Quarterly Focus','price'=>'₦85,000','tag'=>'Best consistency','items'=>['Three months full access','Priority class booking','Monthly body assessment','Membership renewal reminder']],
  ['name'=>'Annual Lifestyle','price'=>'₦340,000','tag'=>'Long-term result','items'=>['12 months full gym access','Member priority support','Quarterly fitness reviews','Exclusive wellness offers']],
];
$classes = [
  ['title'=>'Strength Training','time'=>'Mon/Wed/Fri · 7:30am','desc'=>'Build muscle, improve posture and increase overall body strength.'],
  ['title'=>'Core Cardio','time'=>'Tue/Thu · 8:00am','desc'=>'High-energy cardio and core routine for stamina and fat loss.'],
  ['title'=>'Mobility & Flexibility','time'=>'Wed/Sat · 9:00am','desc'=>'Improve movement, reduce stiffness and support safer training.'],
  ['title'=>'Boxing Fitness','time'=>'Sat · 10:00am','desc'=>'Skill-based boxing drills, endurance work and conditioning.'],
  ['title'=>'Afro Dance Fit','time'=>'Fri · 5:00pm','desc'=>'Fun dance cardio experience with music, sweat and community energy.'],
  ['title'=>'Body Weight Burn','time'=>'Mon · 5:30pm','desc'=>'No-machine full body routines for strength, agility and control.'],
];
$trainers = [
  ['name'=>'Coach Daniel','role'=>'Strength & Conditioning','bio'=>'Helps members build strength, lose fat and follow realistic gym routines.'],
  ['name'=>'Coach Amara','role'=>'Yoga, Mobility & Wellness','bio'=>'Supports flexibility, recovery, posture correction and beginner confidence.'],
  ['name'=>'Coach Femi','role'=>'Boxing & HIIT','bio'=>'Leads boxing fitness, endurance drills and high-intensity conditioning.'],
];
$shop = ['Whey protein','Pre-workout supplements','Gym gloves','Resistance bands','Smart Gym branded shirts','Water bottles'];
?>
<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Smart Gym | Fitness, Training & Wellness Center</title>
<meta name="description" content="Smart Gym is a modern fitness center offering memberships, personal training, online coaching, group classes, gym products and member progress tracking.">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="assets/styles.css?v=smartgym-v1">
</head><body><div class="client-demo-banner">Client demo preview by LynxCom Analytics — sample content only, final website will use the client’s real details.</div>
<header class="site-header"><nav class="nav wrap"><a class="brand" href="#top"><span>SG</span><strong>Smart Gym</strong></a><button class="nav-toggle" type="button" aria-label="Open menu">☰</button><div class="nav-links" id="navLinks"><a href="#plans">Plans</a><a href="#training">Training</a><a href="#classes">Classes</a><a href="#trainers">Trainers</a><a href="#pipeline">Data Pipeline</a><a class="nav-cta" href="#join">Join Now</a></div></nav></header>
<main id="top">
<section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><span class="eyebrow">Modern gym website + LynxCom data pipeline</span><h1>Train smarter, track progress, and grow a stronger fitness community.</h1><p>Smart Gym helps members access fitness plans, personal coaching, online training, classes and wellness support — while the business collects clean data for memberships, payments, attendance and dashboard reporting.</p><div class="hero-actions"><a class="btn primary" href="#join">Start Membership</a><a class="btn secondary" href="#plans">View Plans</a></div><div class="hero-stats"><div><strong>6+</strong><span>Plan options</span></div><div><strong>24/7</strong><span>Online enquiries</span></div><div><strong>100%</strong><span>Data-ready forms</span></div></div></div><div class="hero-card"><div class="pulse"></div><h2>Member Snapshot</h2><ul><li><span>Active members</span><b>248</b></li><li><span>Monthly renewals</span><b>₦4.8m</b></li><li><span>Sessions booked</span><b>312</b></li><li><span>Follow-ups due</span><b>37</b></li></ul><small>Sample dashboard preview for gym management.</small></div></div></section>
<section class="section intro"><div class="wrap intro-grid"><div><span class="kicker">About Smart Gym</span><h2>A professional fitness center built around access, coaching, community and measurable progress.</h2></div><p>Smart Gym serves beginners, professionals, students, fitness lovers and people who need guided routines. Members can choose walk-in plans, subscriptions, physical personal training, online coaching, group classes and fitness products.</p></div></section>
<section class="section plans" id="plans"><div class="wrap"><div class="section-head"><span class="kicker">Membership plans</span><h2>Flexible plans for different fitness goals and budgets.</h2><p>Sample pricing below can be replaced with the client’s real prices before launch.</p></div><div class="plan-grid"><?php foreach($plans as $p): ?><article class="plan <?=!empty($p['featured'])?'featured':''?>"><span class="tag"><?=$p['tag']?></span><h3><?=$p['name']?></h3><p class="price"><?=$p['price']?></p><ul><?php foreach($p['items'] as $item): ?><li><?=$item?></li><?php endforeach; ?></ul><a href="#join">Choose plan →</a></article><?php endforeach; ?></div></div></section>
<section class="section training" id="training"><div class="wrap training-grid"><div><span class="kicker">Training services</span><h2>Physical personal training, online coaching and goal-based fitness guidance.</h2><p>Members can request one-on-one coaching, boxing training, weight loss plans, strength programs, wellness support or remote coaching with structured follow-up.</p><div class="service-list"><div><b>Physical Personal Training</b><span>In-gym coaching, assessments and guided routines.</span></div><div><b>Online Coaching</b><span>Remote training plans, check-ins and consultation support.</span></div><div><b>Group Fitness</b><span>Classes that build motivation, discipline and community.</span></div></div></div><div class="image-panel"><span>Fitness Program Mix</span><div class="bars"><i style="height:82%"></i><i style="height:58%"></i><i style="height:70%"></i><i style="height:44%"></i><i style="height:64%"></i></div></div></div></section>
<section class="section classes" id="classes"><div class="wrap"><div class="section-head"><span class="kicker">Classes</span><h2>Sample class timetable and fitness programs.</h2></div><div class="class-grid"><?php foreach($classes as $c): ?><article><small><?=$c['time']?></small><h3><?=$c['title']?></h3><p><?=$c['desc']?></p></article><?php endforeach; ?></div></div></section>
<section class="section trainers" id="trainers"><div class="wrap"><div class="section-head"><span class="kicker">Trainers</span><h2>Introduce the fitness experts behind the member results.</h2></div><div class="trainer-grid"><?php foreach($trainers as $t): ?><article><div class="avatar"><?=substr($t['name'],6,1)?></div><h3><?=$t['name']?></h3><b><?=$t['role']?></b><p><?=$t['bio']?></p></article><?php endforeach; ?></div></div></section>
<section class="section shop"><div class="wrap shop-box"><div><span class="kicker">Gym shop</span><h2>Fitness products and add-ons.</h2><p>Smart Gym can sell or take enquiries for supplements, branded wears, accessories and training add-ons.</p></div><div class="shop-tags"><?php foreach($shop as $item): ?><span><?=$item?></span><?php endforeach; ?></div></div></section>
<section class="section pipeline" id="pipeline"><div class="wrap pipeline-grid"><div><span class="kicker">LynxCom data pipeline</span><h2>The website is not just for beauty — it becomes the entry point for clean business data.</h2><p>Every form can feed a structured database/spreadsheet so the gym owner sees registrations, renewals, attendance, coaching demand, product enquiries and follow-up lists.</p></div><div class="pipeline-steps"><div><b>01</b><span>Member registration</span></div><div><b>02</b><span>Plan/payment tracking</span></div><div><b>03</b><span>Session & class booking</span></div><div><b>04</b><span>Dashboard visualization</span></div></div></div></section>
<section class="section join" id="join"><div class="wrap join-grid"><div><span class="kicker light">Join Smart Gym</span><h2>Start with a simple registration form.</h2><p>This sample form shows how LynxCom can collect member data cleanly before connecting it to admin dashboards and reports.</p></div><form class="join-form" method="post" action="submit-member.php"><input type="hidden" name="source" value="website"><label>Full name<input name="name" required placeholder="Customer name"></label><label>Phone / WhatsApp<input name="phone" required placeholder="080... / WhatsApp"></label><label>Email<input type="email" name="email" placeholder="email@example.com"></label><label>Preferred plan<select name="plan"><option>Monthly Active</option><option>Day Pass</option><option>Two-Week Reset</option><option>Quarterly Focus</option><option>Annual Lifestyle</option><option>Personal Training</option><option>Online Coaching</option></select></label><label>Fitness goal<textarea name="goal" placeholder="Weight loss, muscle gain, fitness habit, boxing, wellness..."></textarea></label><button class="btn primary wide">Submit registration</button></form></div></section>
</main><footer class="footer"><div class="wrap footer-grid"><div><strong>Smart Gym</strong><p>Fitness, coaching, classes and member progress tracking.</p></div><div><span><?=$phone?></span><span><?=$email?></span><span>Sample location, Nigeria</span></div></div></footer><script src="assets/script.js?v=smartgym-v1"></script></body></html>
