<?php
$products=[
 ['category'=>'Supplements','items'=>[
  ['name'=>'Whey Protein','price'=>'From ₦38,000','img'=>'assets/img/products/whey-protein-20260911.webp','desc'=>'Protein support for recovery, lean muscle and daily nutrition.'],
  ['name'=>'Pre-Workout','price'=>'From ₦22,000','img'=>'assets/img/products/pre-workout-20260911.webp','desc'=>'Energy and focus support before intense training sessions.'],
  ['name'=>'Creatine Monohydrate','price'=>'From ₦18,000','img'=>'assets/img/products/creatine-20260911.webp','desc'=>'Strength and performance support for consistent gym members.'],
  ['name'=>'Shaker Bottle','price'=>'From ₦4,500','img'=>'assets/img/products/shaker-bottle-20260911.webp','desc'=>'Easy mixing bottle for protein shakes and workout drinks.'],
 ]],
 ['category'=>'Training Accessories','items'=>[
  ['name'=>'Gym Gloves','price'=>'From ₦8,500','img'=>'assets/img/products/gym-gloves-20260911.webp','desc'=>'Grip protection for weights, pull exercises and general training.'],
  ['name'=>'Resistance Bands','price'=>'From ₦6,000','img'=>'assets/img/products/resistance-bands-20260911.webp','desc'=>'Portable support for warmups, mobility and strength routines.'],
  ['name'=>'Skipping Rope','price'=>'From ₦5,500','img'=>'assets/img/products/skipping-rope-20260911.webp','desc'=>'Cardio tool for endurance, speed and conditioning.'],
  ['name'=>'Lifting Belt','price'=>'From ₦20,000','img'=>'assets/img/products/lifting-belt-20260911.webp','desc'=>'Waist support for heavy lifting and strength training.'],
 ]],
 ['category'=>'Gym Wear','items'=>[
  ['name'=>'Training T-Shirt','price'=>'From ₦12,000','img'=>'assets/img/products/training-shirt-20260911.webp','desc'=>'Comfortable breathable gym top for daily workouts.'],
  ['name'=>'Joggers / Training Pants','price'=>'From ₦18,000','img'=>'assets/img/products/joggers-20260911.webp','desc'=>'Flexible training wear for mobility, warmups and gym sessions.'],
  ['name'=>'Sports Towel','price'=>'From ₦4,000','img'=>'assets/img/products/sports-towel-20260911.webp','desc'=>'Workout towel for gym floor and class sessions.'],
  ['name'=>'Gym Bag','price'=>'From ₦25,000','img'=>'assets/img/products/gym-bag-20260911.webp','desc'=>'Carry training gear, shoes, towel and supplements.'],
 ]],
];
function h($v){return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Smart Shape Fitness Gym Shop | Products & Fitness Items</title><meta name="description" content="Browse Smart Shape Fitness Gym shop items including supplements, gym accessories, training wear and service enquiries."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/styles.css?v=smartshape-section-left-20260912"></head><body><header class="sg-header"><a class="sg-logo" href="index.php#top"><img class="brand-logo" src="assets/img/smart-shape-professional-logo.jpg" alt="Smart Shape Fitness Gym professional logo"><b>SMART SHAPE</b></a><button class="mobile-menu-toggle" type="button" aria-expanded="false" aria-controls="site-menu">Menu</button><nav id="site-menu"><a href="index.php#top">Home</a><a href="index.php#memberships">Membership Plans</a><a href="index.php#programs">Programs</a><a href="index.php#schedule">Schedule</a><a href="shop.php">Shop</a><a href="index.php#coaches">Trainers</a><a href="index.php#join">Join</a></nav><a class="header-btn" href="index.php#join">Start Now</a></header><main><section class="shop-hero"><div><span class="label">Smart Shape Fitness Gym Shop</span><h1>Training essentials, products and fitness items.</h1><p>Browse available product categories and send an enquiry for supplements, accessories or gym wear.</p><div class="hero-actions"><a class="btn fire" href="#products">View Items</a><a class="btn ghost" href="index.php#join">Make Enquiry</a></div></div><figure><img src="assets/img/shop-naija-v2-20260911.webp" alt="Smart Shape Fitness Gym shop and fitness products" loading="eager" decoding="async"></figure></section><section class="shop-page-products" id="products"><?php foreach($products as $group): ?><div class="shop-category"><div class="section-title"><span><?=h($group['category'])?></span><h2><?=h($group['category'])?></h2></div><div class="shop-item-grid"><?php foreach($group['items'] as $item): ?><article><img class="product-thumb" src="<?=h($item['img'])?>" alt="<?=h($item['name'])?> at Smart Shape Fitness Gym shop" loading="lazy" decoding="async"><h3><?=h($item['name'])?></h3><b><?=h($item['price'])?></b><p><?=h($item['desc'])?></p><a href="index.php#join">Enquire</a></article><?php endforeach; ?></div></div><?php endforeach; ?></section></main><footer class="sg-footer"><b>SMART SHAPE</b><span>Smart Shape Fitness Gym · Train stronger. Shape better. Stay consistent.</span></footer><script src="assets/script.js?v=smartshape-section-left-20260912"></script></body></html>
