<?php
require __DIR__.'/includes/functions.php';
track_visit('Foundation package intake');
$c=load_content();
$name=trim($_GET['name']??''); $phone=trim($_GET['phone']??''); $email=trim($_GET['email']??''); $business=trim($_GET['business']??'');
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Business Data Foundation & Tracking System Intake | Lynxcom Analytics</title>
<link rel="canonical" href="https://lynxcomanalytics.com/foundation-intake.php">
<meta name="robots" content="noindex,nofollow">
<meta name="description" content="Business Data Foundation & Tracking System intake for businesses that need record structure before dashboard insights.">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/styles.css?v=foundation-intake-20260828">
</head>
<body><header class="site-header"><nav class="nav wrap"><a class="brand brand-logo" href="/"><img src="assets/lynxcom-logo.svg" alt="Lynxcom Analytics logo"></a><button class="nav-toggle" aria-label="Open menu">☰</button><div class="nav-links" id="navLinks"><a href="/#services">Services</a><a href="/#packages">Packages</a><a href="blog.php">Blog</a><a href="support.php">Support</a><a href="/#contact" class="nav-cta">Book consultation</a><div class="nav-contact"><span>Contact</span><a href="tel:+2348136377667">+234 813 637 7667</a><a href="mailto:hello@lynxcomanalytics.com">hello@lynxcomanalytics.com</a></div></div></nav></header>
<main>
<section class="starter-intake-hero growth-intake-hero"><div class="wrap"><span class="kicker">Foundation Package</span><h1>Business Data Foundation & Tracking System</h1><p>This package is for businesses that do not yet have proper records. Lynxcom first helps you create the right structure for sales, customers, expenses, payments, staff tasks and follow-ups before promising dashboard insights.</p></div></section>
<section class="starter-intake-section"><div class="wrap starter-intake-shell"><aside class="starter-intake-note"><h2>What this package creates</h2><ul><li>Daily sales and customer record structure</li><li>Payment, debtor and expense trackers</li><li>Follow-up and task tracking system</li><li>Simple weekly management report format</li><li>Team usage guide and adoption support</li><li>Dashboard-readiness roadmap</li></ul><p><strong>Note:</strong> Do not enter passwords, OTPs, card details, API keys, or private login credentials.</p></aside>
<form class="starter-intake-form growth-intake-form" method="post" action="submit-foundation-intake.php"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input class="hidden" name="website" tabindex="-1" autocomplete="off">
<fieldset><legend>1. Contact & business identity</legend><div class="form-row"><label>Your full name<input name="lead_name" required value="<?=h($name)?>"></label><label>Phone / WhatsApp<input name="lead_phone" required value="<?=h($phone)?>"></label></div><div class="form-row"><label>Email address<input type="email" name="lead_email" value="<?=h($email)?>"></label><label>Business / organization name<input name="business_name" required value="<?=h($business)?>"></label></div><div class="form-row"><label>Your role<input name="role" placeholder="Owner, manager, admin, operations lead..."></label><label>Industry / type of business<input name="industry" required></label></div><div class="form-row"><label>Location<input name="location"></label><label>Years active<input name="years_active"></label></div><div class="form-row"><label>Staff count<input name="staff_count"></label><label>Branches/locations<input name="branches"></label></div></fieldset>
<fieldset><legend>2. Current record situation</legend><label>Which best describes your records now?<select name="current_record_status" required><option value="">Select one</option><option>No structured records yet</option><option>Mostly notebook/paper records</option><option>Mostly WhatsApp/verbal updates</option><option>Some scattered Excel/Google Sheets</option><option>POS/app reports but no internal tracker</option></select></label><label>Why are proper records not available yet?<textarea name="why_no_records" placeholder="No one assigned, no template, staff not consistent, unsure what to track..."></textarea></label><label>Current tools used, if any<textarea name="current_tools" placeholder="Notebook, WhatsApp, POS reports, Excel, Google Sheets, receipts, invoices..."></textarea></label></fieldset>
<fieldset><legend>3. What needs to be tracked</legend><label>How do you currently record daily sales or jobs?<textarea name="daily_sales_process"></textarea></label><label>How do you capture customer/client details?<textarea name="customer_capture_process"></textarea></label><div class="form-row"><label>Payment tracking status<textarea name="payment_tracking_status"></textarea></label><label>Expense tracking status<textarea name="expense_tracking_status"></textarea></label></div><div class="form-row"><label>Stock/product/service tracking<textarea name="stock_or_service_tracking"></textarea></label><label>Staff/task tracking<textarea name="staff_task_tracking"></textarea></label></div><label>Follow-up tracking status<textarea name="followup_tracking_status" placeholder="How do you know who to call/message, who has paid, who is pending, who needs attention?"></textarea></label><label>Debtors or pending payments situation<textarea name="debtors_or_pending_payments"></textarea></label></fieldset>
<fieldset><legend>4. System design & adoption</legend><label>What reports should management see weekly?<textarea name="reports_needed" placeholder="Sales summary, customer follow-up, expenses, stock, staff tasks, payment status..."></textarea></label><div class="form-row"><label>Who will update the records?<input name="people_who_will_update" placeholder="Owner, cashier, admin, manager, staff..."></label><label>How often should records be updated?<select name="update_frequency"><option value="">Select one</option><option>Daily</option><option>After every sale/customer interaction</option><option>Weekly</option><option>Not sure yet</option></select></label></div><label>Training needed<textarea name="training_needed" placeholder="Who needs to be trained and what do they struggle with?"></textarea></label><label>Preferred tool<select name="preferred_tool"><option value="">Select one</option><option>Google Sheets</option><option>Excel</option><option>Airtable/Notion</option><option>Simple online form + tracker</option><option>Recommend the best option</option></select></label><label>Which modules should the foundation include?<textarea name="foundation_modules" placeholder="Sales tracker, customer tracker, expense tracker, payment/debtor tracker, staff task tracker, follow-up tracker, weekly report..."></textarea></label></fieldset>
<fieldset><legend>5. Dashboard/automation roadmap</legend><label>What would you like automated later?<textarea name="automation_interest" placeholder="Follow-up reminders, WhatsApp/SMS/email workflow, staff reminders, payment chasing, weekly report generation..."></textarea></label><label>What dashboard or insight would you want after records become consistent?<textarea name="dashboard_later_goal" placeholder="Best customers, sales trend, expenses, staff performance, pending payments, follow-up due..."></textarea></label><label>What will make this Foundation package successful for you?<textarea name="success_definition" required></textarea></label><div class="form-row"><label>Budget confirmation<select name="budget_confirmed" required><option value="">Select one</option><option>I understand Foundation is ₦180k–₦350k</option><option>I need final quote after review</option><option>I may need Growth/Premium after the foundation is ready</option></select></label><label>Timeline<select name="timeline" required><option value="">Select one</option><option>Urgent: start this week</option><option>Within 2–4 weeks</option><option>This month</option><option>Planning ahead</option></select></label></div><div class="form-row"><label>Decision maker<input name="decision_maker" placeholder="Who approves the project/payment?"></label><label>Privacy consent<select name="privacy_consent" required><option value="">Select one</option><option>I agree to share only business records needed for scoping</option></select></label></div><label>Extra notes<textarea name="extra_notes"></textarea></label></fieldset>
<button class="btn primary wide premium-submit">Submit Foundation intake</button>
</form></div></section></main><footer class="footer wrap"><div><strong>Lynxcom Analytics</strong><p>Business dashboards, reporting and workflow automation.</p></div><div class="footer-links"><a href="/">Home</a><a href="blog.php">Blog</a><a href="support.php">Support</a></div></footer><script src="assets/script.js?v=foundation-intake-20260828"></script></body></html>
