<?php
require __DIR__.'/includes/functions.php';
track_visit('Foundation package thank you');
$c=load_content();
$name=trim($_GET['name']??'');
$business=trim($_GET['business']??'');
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Foundation Intake Received | Lynxcom Analytics</title>
<link rel="canonical" href="https://lynxcomanalytics.com/foundation-thank-you.php">
<meta name="robots" content="noindex,nofollow">
<meta name="description" content="Thank you page for Lynxcom Analytics Business Data Foundation & Tracking System intake submissions.">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/styles.css?v=foundation-thank-you-20260828">
</head>
<body><header class="site-header"><nav class="nav wrap"><a class="brand brand-logo" href="/"><img src="assets/lynxcom-logo.svg" alt="Lynxcom Analytics logo"></a><button class="nav-toggle" aria-label="Open menu">☰</button><div class="nav-links" id="navLinks"><a href="/#services">Services</a><a href="/#packages">Packages</a><a href="blog.php">Blog</a><a href="support.php">Support</a><a href="/#contact" class="nav-cta">Book consultation</a><div class="nav-contact"><span>Contact</span><a href="tel:+2348136377667">+234 813 637 7667</a><a href="mailto:hello@lynxcomanalytics.com">hello@lynxcomanalytics.com</a></div></div></nav></header>
<main>
<section class="starter-thank-hero growth-thank-hero"><div class="wrap starter-thank-wrap"><div class="starter-thank-copy"><span class="kicker">Foundation Intake Received</span><h1>Thank you<?= $name ? ', '.h($name) : '' ?>. Your Foundation intake is in.</h1><p><?= $business ? 'We have received the Business Data Foundation details for <strong>'.h($business).'</strong>.' : 'We have received your Business Data Foundation & Tracking System details.' ?> Lynxcom Analytics will review your current record situation and recommend the right structure before dashboard insights are promised.</p><div class="starter-thank-actions"><a class="btn primary" href="mailto:hello@lynxcomanalytics.com">Email Lynxcom</a><a class="btn ghost" href="https://wa.me/2348136377667">Chat on WhatsApp</a></div></div><aside class="starter-thank-status"><div class="checkmark">✓</div><h2>Submission confirmed</h2><p>Your answers have been saved for review. Please do not send passwords, OTPs, card details, API keys, or login credentials.</p></aside></div></section>
<section class="starter-next-section growth-next-section"><div class="wrap"><div class="section-head compact"><span class="kicker">What happens next</span><h2>Your Foundation setup process</h2><p>These steps help Lynxcom create a usable record structure before dashboard or automation work begins.</p></div><div class="starter-next-grid"><article><b>1</b><h3>Record gap review</h3><p>We review how your business currently handles sales, customers, payments, expenses, tasks and follow-ups.</p></article><article><b>2</b><h3>Tracking structure design</h3><p>We design the right templates/forms for daily records, customer lists, debtor/payment tracking, staff tasks and weekly reporting.</p></article><article><b>3</b><h3>Training and adoption</h3><p>We guide the owner/team on what to enter, who updates it, when to update it, and how to avoid inconsistent records.</p></article><article><b>4</b><h3>Dashboard readiness</h3><p>Once records become consistent, Lynxcom can turn them into dashboards, automated follow-up and management reports.</p></article></div></div></section>
<section class="starter-records-section growth-records-section"><div class="wrap starter-records-box"><div><span class="kicker light">Prepare safely</span><h2>Information you may be asked to prepare</h2><p>Only provide business process details and safe sample records. Do not send passwords, OTPs, card details, API keys, or private login credentials.</p></div><div class="starter-records-list"><span>Sales process</span><span>Customer details needed</span><span>Payment/debtor process</span><span>Expense categories</span><span>Staff/task roles</span><span>Follow-up routine</span><span>Report needs</span><span>Preferred tool</span></div></div></section>
</main><footer class="footer wrap"><div><strong>Lynxcom Analytics</strong><p>Business data foundation, dashboards and workflow automation.</p></div><div class="footer-links"><a href="/">Home</a><a href="blog.php">Blog</a><a href="support.php">Support</a></div></footer><script src="assets/script.js?v=foundation-thank-you-20260828"></script></body></html>
