<?php
require __DIR__.'/includes/functions.php';
track_visit('Growth package thank you');
$c=load_content();
$name=trim($_GET['name']??'');
$business=trim($_GET['business']??'');
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Growth Intake Received | Lynxcom Analytics</title>
<link rel="canonical" href="https://lynxcomanalytics.com/growth-thank-you.php">
<meta name="robots" content="noindex,nofollow">
<meta name="description" content="Thank you page for Lynxcom Analytics Growth Dashboard & Workflow System intake submissions.">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/styles.css?v=growth-thank-you-20260827">
</head>
<body><header class="site-header"><nav class="nav wrap"><a class="brand brand-logo" href="/"><img src="assets/lynxcom-logo.svg" alt="Lynxcom Analytics logo"></a><button class="nav-toggle" aria-label="Open menu">☰</button><div class="nav-links" id="navLinks"><a href="/#services">Services</a><a href="/#packages">Packages</a><a href="project-samples.php">Projects</a><a href="blog.php">Blog</a><a href="support.php">Support</a><a href="/#contact" class="nav-cta">Book consultation</a><div class="nav-contact"><span>Contact</span><a href="tel:+234****7667">+234 813 637 7667</a><a href="mailto:hello@lynxcomanalytics.com">hello@lynxcomanalytics.com</a></div></div></nav></header>
<main>
<section class="starter-thank-hero growth-thank-hero"><div class="wrap starter-thank-wrap"><div class="starter-thank-copy"><span class="kicker">Growth Intake Received</span><h1>Thank you<?= $name ? ', '.h($name) : '' ?>. Your Growth intake is in.</h1><p><?= $business ? 'We have received the Growth Dashboard & Workflow System details for <strong>'.h($business).'</strong>.' : 'We have received your Growth Dashboard & Workflow System details.' ?> Lynxcom Analytics will review your answers and contact you with the next step.</p><div class="starter-thank-actions"><a class="btn primary" href="mailto:hello@lynxcomanalytics.com">Email Lynxcom</a><a class="btn ghost" href="https://wa.me/2348136377667">Chat on WhatsApp</a></div></div><aside class="starter-thank-status"><div class="checkmark">✓</div><h2>Submission confirmed</h2><p>Your answers have been saved for review. Please do not send passwords, OTPs, card details, API keys, or private login credentials.</p></aside></div></section>
<section class="starter-next-section growth-next-section"><div class="wrap"><div class="section-head compact"><span class="kicker">What happens next</span><h2>Your Growth system scoping process</h2><p>These are the next steps before Lynxcom confirms your dashboard, trackers, workflow system, and implementation scope.</p></div><div class="starter-next-grid"><article><b>1</b><h3>Submission review</h3><p>Lynxcom reviews your business identity, decision process, data sources, current tools, reporting needs, workflow bottlenecks, and success targets.</p></article><article><b>2</b><h3>Scope clarification</h3><p>We may contact you to clarify dashboard pages, tracker modules, automation needs, access roles, reports, timeline, and budget fit.</p></article><article><b>3</b><h3>Safe sample records request</h3><p>If needed, we will request safe sample exports/files such as Excel, CSV, Google Sheets, PDF reports, POS/app exports, screenshots, or current trackers.</p></article><article><b>4</b><h3>Implementation roadmap</h3><p>You receive the confirmed Growth scope, fee guidance within the ₦200k–₦500k range, delivery phases, and the next onboarding step.</p></article></div></div></section>
<section class="starter-records-section growth-records-section"><div class="wrap starter-records-box"><div><span class="kicker light">Prepare safely</span><h2>Records you may be asked to share</h2><p>Only send business records needed for scoping or agreed implementation. Do not send passwords, OTPs, card details, API keys, or private login credentials.</p></div><div class="starter-records-list"><span>Sales records</span><span>Customer list</span><span>Payment/debtor tracker</span><span>Inventory/stock records</span><span>Staff/task tracker</span><span>Expense records</span><span>Branch reports</span><span>Excel/CSV exports</span><span>Google Sheets links</span><span>POS/app exports</span><span>PDF reports</span><span>Screenshots if files are unavailable</span></div></div></section>
</main><footer class="footer wrap"><div><strong>Lynxcom Analytics</strong><p>Business dashboards, reporting and workflow automation.</p></div><div class="footer-links"><a href="/">Home</a><a href="blog.php">Blog</a><a href="support.php">Support</a></div></footer><script src="assets/script.js?v=growth-thank-you-20260827"></script></body></html>
