<?php require __DIR__.'/includes/functions.php'; $c=load_content(); $wa=preg_replace('/\D/','',$c['whatsapp']??'2348136377667'); ?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($c['brand']??'Lynxcom Analytics')?> | <?=h($c['tagline']??'AI-Powered Business Dashboard & Automation Consulting')?></title><meta name="description" content="<?=h($c['subheadline']??'AI dashboards and automation consulting')?>"><meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate"><meta http-equiv="Pragma" content="no-cache"><meta http-equiv="Expires" content="0"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@300;400;500;600;700&family=Source+Code+Pro:wght@400;500;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/styles.css?v=carousel-final-20260824"></head>
<body><header class="site-header"><nav class="nav wrap"><a class="brand brand-logo" href="#top"><img src="assets/lynxcom-logo.svg" alt="<?=h($c['brand']??'Lynxcom Analytics')?> logo"></a><button class="nav-toggle" aria-label="Open menu">☰</button><div class="nav-links" id="navLinks"><a href="#services">Services</a><a href="#process">Process</a><a href="#packages">Packages</a><a href="#contact" class="nav-cta">Book consultation</a></div></nav></header>
<main id="top">
<section class="lx-hero-carousel" aria-label="Lynxcom Analytics homepage slider">
  <div class="lx-carousel-track">
    <article class="lx-slide">
      <img src="assets/slider-dashboard.jpg" alt="Black African business team reviewing dashboard analytics">
      <div class="lx-slide-shade"></div>
      <div class="lx-slide-content wrap">
        <span>Dashboard clarity</span>
        <h1>See your business clearly. Act faster with data.</h1>
        <p>We turn scattered records into clear dashboards, automated workflows and smarter management decisions.</p>
        <div class="lx-slide-actions"><a class="btn primary" href="#services">View dashboard service</a><a class="btn lx-glass" href="#contact">Request consultation</a></div>
      </div>
    </article>
    <article class="lx-slide">
      <img src="assets/slider-automation.jpg" alt="Black African entrepreneur using automation workflow tools">
      <div class="lx-slide-shade"></div>
      <div class="lx-slide-content wrap">
        <span>Workflow automation</span>
        <h1>Reduce repetitive admin and follow-up stress.</h1>
        <p>We map practical AI workflows for reports, reminders, customer follow-up and daily operations.</p>
        <div class="lx-slide-actions"><a class="btn primary" href="#services">View automation service</a><a class="btn lx-glass" href="#process">See process</a></div>
      </div>
    </article>
    <article class="lx-slide">
      <img src="assets/slider-reporting.jpg" alt="Black African executives reviewing weekly business report">
      <div class="lx-slide-shade"></div>
      <div class="lx-slide-content wrap">
        <span>Management reporting</span>
        <h1>Turn reports into decisions and next actions.</h1>
        <p>Get weekly views that show what improved, what dropped and what needs urgent attention.</p>
        <div class="lx-slide-actions"><a class="btn primary" href="#packages">View reporting packages</a><a class="btn lx-glass" href="#contact">Book consultation</a></div>
      </div>
    </article>
  </div>
  <button class="lx-carousel-btn lx-prev" type="button" aria-label="Previous slide">‹</button>
  <button class="lx-carousel-btn lx-next" type="button" aria-label="Next slide">›</button>
  <div class="lx-carousel-dots"><button class="active" type="button" aria-label="Show slide 1"></button><button type="button" aria-label="Show slide 2"></button><button type="button" aria-label="Show slide 3"></button></div>
</section>
<section class="hero wrap intro-hero"><div class="hero-copy"><div class="eyebrow"><span></span><?=h($c['tagline']??'AI dashboards')?></div><h1><?=h($c['headline']??'Build a smarter business system')?></h1><p class="lead"><?=h($c['subheadline']??'We organize business data and automate repetitive reporting.')?></p><div class="hero-actions"><a class="btn primary" target="_blank" rel="noopener" href="https://wa.me/<?=$wa?>?text=Hi%2C%20I%20want%20an%20AI-powered%20dashboard%20and%20automation%20system">Chat on WhatsApp</a><a class="btn ghost" href="#contact">Request consultation</a></div><div class="trust-row"><?php foreach(array_slice($c['industries']??[],0,5) as $i): ?><span><?=h($i)?></span><?php endforeach; ?></div></div><div class="hero-panel"><div class="panel-top"><span></span><span></span><span></span><b>Business Command Center</b></div><div class="metric-grid"><div class="metric"><small>Revenue tracked</small><strong>₦24.8M</strong><em>+18% this month</em></div><div class="metric"><small>Follow-ups due</small><strong>42</strong><em>High priority</em></div><div class="metric"><small>Manual hours saved</small><strong>16h</strong><em>Weekly estimate</em></div></div><div class="chart-card"><div class="bars"><i style="height:45%"></i><i style="height:72%"></i><i style="height:52%"></i><i style="height:88%"></i><i style="height:64%"></i><i style="height:94%"></i></div></div><div class="task-list"><p><span class="check">✓</span> Weekly report generated</p><p><span class="check">✓</span> Customer list cleaned</p><p><span class="warn">!</span> 12 inactive customers need action</p></div></div></section>
<section class="section wrap" id="services"><div class="section-head"><span class="kicker">What we do</span><h2>One broad service for business clarity and operational speed.</h2><p>We combine dashboards, reporting systems and AI automation consulting into a practical service that makes operations easier to manage.</p></div><div class="cards six"><?php foreach($c['services']??[] as $s): ?><article class="card"><span class="icon"><?=h($s['icon']??'•')?></span><h3><?=h($s['title']??'Service')?></h3><p><?=h($s['body']??'')?></p></article><?php endforeach; ?></div></section>
<section class="dark-section"><div class="wrap split"><div><span class="kicker light">Business outcomes</span><h2>We build systems that help owners manage better.</h2><p>Clients get clear visibility, less manual reporting stress, better follow-up discipline and smarter decisions from their own records.</p></div><div class="outcome-list"><div><strong>01</strong><span>Know what is happening in the business.</span></div><div><strong>02</strong><span>See what needs attention this week.</span></div><div><strong>03</strong><span>Automate repetitive admin and reporting work.</span></div><div><strong>04</strong><span>Turn reports into daily action lists.</span></div></div></div></section>
<section class="section wrap"><div class="section-head compact"><span class="kicker">Who we serve</span><h2>Built for businesses that run on customers, records and regular follow-up.</h2></div><div class="pill-grid"><?php foreach($c['industries']??[] as $i): ?><span><?=h($i)?></span><?php endforeach; ?></div></section>
<section class="section wrap" id="process"><div class="section-head"><span class="kicker">How it works</span><h2>From messy data to a working system.</h2></div><div class="timeline"><div><b>1</b><h3>Business review</h3><p>We understand records, reporting pain, goals and workflow.</p></div><div><b>2</b><h3>Data preparation</h3><p>We clean and structure the available data.</p></div><div><b>3</b><h3>Dashboard build</h3><p>We build a KPI tracker that shows performance and trends.</p></div><div><b>4</b><h3>Automation map</h3><p>We design reminders, reports and follow-up workflows.</p></div><div><b>5</b><h3>Support</h3><p>We train the client and offer monthly reporting support.</p></div></div></section>
<section class="section wrap" id="packages"><div class="section-head"><span class="kicker">Packages</span><h2>Choose the level of clarity and automation your business needs.</h2></div><div class="pricing-grid"><?php foreach($c['packages']??[] as $p): ?><article class="price-card <?=!empty($p['featured'])?'featured':''?>"><span class="badge"><?=h($p['name']??'Package')?></span><h3><?=h($p['title']??'Package')?></h3><p class="price"><?=h($p['price']??'Custom')?></p><ul><?php foreach($p['items']??[] as $item): ?><li><?=h($item)?></li><?php endforeach; ?></ul><a href="#contact">Request this package →</a></article><?php endforeach; ?></div></section>
<section class="section wrap" id="security"><div class="section-head compact"><span class="kicker">Security & privacy</span><h2>We treat business data carefully.</h2><p>We do not ask clients to send passwords or OTPs. Clients can provide exports, spreadsheets, PDFs or limited-access data. Customer data is used only for the agreed project scope.</p></div><div class="security-grid"><div><b>No passwords required</b><span>Clients export data or log in themselves where necessary.</span></div><div><b>Private delivery</b><span>Dashboards can be password-protected or kept inside the client’s Google/Excel environment.</span></div><div><b>Approval before outreach</b><span>No SMS, email or WhatsApp campaign goes out without client approval.</span></div></div></section>
<section class="cta-section" id="contact"><div class="wrap cta-box"><div><span class="kicker light">Ready to organize your business?</span><h2>Book a consultation for your dashboard and automation system.</h2><p>Tell us what you currently track and what is stressful. We will recommend the right dashboard, workflow and automation plan.</p></div><div class="contact-card"><?php if(isset($_GET['sent'])): ?><div class="success-msg">Thank you. Your request has been received.</div><?php endif; ?><form method="post" action="submit-lead.php"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input class="hidden" name="website" tabindex="-1" autocomplete="off"><input name="name" placeholder="Your name" required><input name="phone" placeholder="Phone / WhatsApp" required><input type="email" name="email" placeholder="Email address"><input name="business" placeholder="Business / organization name"><select name="service"><option>Dashboard & automation consulting</option><option>Dashboard setup</option><option>Data cleanup</option><option>Reporting automation</option><option>Customer follow-up system</option></select><select name="budget"><option>Budget range</option><option>₦75k–₦150k</option><option>₦200k–₦500k</option><option>₦600k+</option></select><textarea name="message" placeholder="What do you want to improve or automate?" required></textarea><button class="btn primary wide">Send enquiry</button></form><p><strong>WhatsApp / Calls:</strong><br><?=h($c['phone_primary']??'')?> · <?=h($c['phone_secondary']??'')?></p><p><strong>Email:</strong><br><a href="mailto:<?=h($c['email']??'')?>"><?=h($c['email']??'')?></a></p></div></div></section></main><footer class="footer wrap"><div><strong><?=h($c['brand']??'Lynxcom Analytics')?></strong><p><?=h($c['tagline']??'AI business systems')?></p></div><div class="footer-links"><a href="#services">Services</a><a href="#packages">Packages</a><a href="admin/login.php">Admin</a></div></footer><script src="assets/script.js?v=carousel-final-20260824"></script></body></html>