<?php
require __DIR__.'/includes/functions.php';
track_visit('Premium package thank you');
$c=load_content();
$name=trim($_GET['name']??'');
$business=trim($_GET['business']??'');
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Premium Intake Received | Lynxcom Analytics</title>
<link rel="canonical" href="https://lynxcomanalytics.com/premium-thank-you.php">
<meta name="robots" content="noindex,nofollow">
<meta name="description" content="Thank you page for Lynxcom Analytics Premium AI Operations System intake submissions.">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/styles.css?v=premium-thank-you-20260827">
</head>
<body><header class="site-header"><nav class="nav wrap"><a class="brand brand-logo" href="/"><img src="assets/lynxcom-logo.svg" alt="Lynxcom Analytics logo"></a><button class="nav-toggle" aria-label="Open menu">☰</button><div class="nav-links" id="navLinks"><a href="/#services">Services</a><a href="/#packages">Packages</a><a href="blog.php">Blog</a><a href="support.php">Support</a><a href="/#contact" class="nav-cta">Book consultation</a><div class="nav-contact"><span>Contact</span><a href="tel:+234****7667">+234 813 637 7667</a><a href="mailto:hello@lynxcomanalytics.com">hello@lynxcomanalytics.com</a></div></div></nav></header>
<main>
<section class="starter-thank-hero growth-thank-hero"><div class="wrap starter-thank-wrap"><div class="starter-thank-copy"><span class="kicker">Premium Intake Received</span><h1>Thank you<?= $name ? ', '.h($name) : '' ?>. Your Premium intake is in.</h1><p><?= $business ? 'We have received the Premium AI Operations System details for <strong>'.h($business).'</strong>.' : 'We have received your Premium AI Operations System details.' ?> Lynxcom Analytics will review your answers and contact you with the next scoping step.</p><div class="starter-thank-actions"><a class="btn primary" href="mailto:hello@lynxcomanalytics.com">Email Lynxcom</a><a class="btn ghost" href="https://wa.me/2348136377667">Chat on WhatsApp</a></div></div><aside class="starter-thank-status"><div class="checkmark">✓</div><h2>Submission confirmed</h2><p>Your answers have been saved for review. Please do not send passwords, OTPs, card details, API keys, or private login credentials.</p></aside></div></section>
<section class="starter-next-section growth-next-section"><div class="wrap"><div class="section-head compact"><span class="kicker">What happens next</span><h2>Your Premium scoping process</h2><p>These are the next steps before Lynxcom confirms your AI operations system scope, timeline, access method and implementation roadmap.</p></div><div class="starter-next-grid"><article><b>1</b><h3>Deep submission review</h3><p>Lynxcom reviews your departments, records, workflows, dashboards, AI use cases, integrations, security needs and success definition.</p></article><article><b>2</b><h3>Executive scoping call</h3><p>We may schedule a call with the business owner, project sponsor, data owner and key department leads to confirm scope.</p></article><article><b>3</b><h3>Safe data walkthrough</h3><p>If needed, we request safe sample exports/files or a screen-share walkthrough. We do not need passwords, OTPs or private credentials.</p></article><article><b>4</b><h3>Premium roadmap</h3><p>You receive the confirmed system plan, delivery phases, budget guidance, implementation timeline, training approach and review structure.</p></article></div></div></section>
<section class="starter-records-section growth-records-section"><div class="wrap starter-records-box"><div><span class="kicker light">Prepare safely</span><h2>Records you may be asked to share</h2><p>Only send business records needed for scoping or agreed implementation. Do not send passwords, OTPs, card details, API keys, or private login credentials.</p></div><div class="starter-records-list"><span>Department records</span><span>Sales/customer data</span><span>Payment/debtor records</span><span>Inventory/stock records</span><span>Staff/task records</span><span>Branch reports</span><span>Current dashboards</span><span>SOP/process docs</span><span>Excel/CSV exports</span><span>Google Sheets links</span><span>App/POS exports</span><span>PDF reports</span><span>Screenshots if files are unavailable</span></div></div></section>
</main><footer class="footer wrap"><div><strong>Lynxcom Analytics</strong><p>Business dashboards, reporting and workflow automation.</p></div><div class="footer-links"><a href="/">Home</a><a href="blog.php">Blog</a><a href="support.php">Support</a></div></footer><script src="assets/script.js?v=premium-thank-you-20260827"></script></body></html>
