<?php
require __DIR__.'/includes/functions.php';
track_visit('Starter package intake');
$c=load_content();
$name=trim($_GET['name']??''); $phone=trim($_GET['phone']??''); $email=trim($_GET['email']??''); $business=trim($_GET['business']??'');
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Starter Package Intake | Lynxcom Analytics</title>
<link rel="canonical" href="https://lynxcomanalytics.com/starter-intake.php">
<meta name="robots" content="noindex,nofollow">
<meta name="description" content="Starter package intake questionnaire for Lynxcom Analytics Dashboard & Automation Audit clients.">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@300;400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/styles.css?v=starter-intake-20260825">
</head>
<body><header class="site-header"><nav class="nav wrap"><a class="brand brand-logo" href="/"><img src="assets/lynxcom-logo.svg" alt="Lynxcom Analytics logo"></a><button class="nav-toggle" aria-label="Open menu">☰</button><div class="nav-links" id="navLinks"><a href="/#services">Services</a><a href="/#packages">Packages</a><a href="project-samples.php">Projects</a><a href="blog.php">Blog</a><a href="support.php">Support</a><a href="/#contact" class="nav-cta">Book consultation</a><div class="nav-contact"><span>Contact</span><a href="tel:+2348136377667">+234 813 637 7667</a><a href="mailto:hello@lynxcomanalytics.com">hello@lynxcomanalytics.com</a></div></div></nav></header>
<main>
<section class="starter-intake-hero"><div class="wrap"><span class="kicker">Starter Package</span><h1>Dashboard & Automation Audit Intake</h1><p>This form helps Lynxcom Analytics understand your business records, reporting problems, KPIs, and automation opportunities before your Starter audit begins. Please answer as fully as possible.</p><?php if(isset($_GET['sent'])): ?><div class="success-msg">Thank you. Your Starter package questionnaire has been submitted.</div><?php endif; ?></div></section>
<section class="starter-intake-section"><div class="wrap starter-intake-shell"><aside class="starter-intake-note"><h2>What this covers</h2><ul><li>Business process review</li><li>Current data and reporting setup</li><li>KPI and dashboard needs</li><li>Data cleanup readiness</li><li>Automation opportunities</li><li>Audit goals, timeline and next action</li></ul><p><strong>Note:</strong> Do not enter passwords, OTPs, card details, or private login credentials.</p></aside>
<form class="starter-intake-form" method="post" action="submit-starter-intake.php"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input class="hidden" name="website" tabindex="-1" autocomplete="off">
<fieldset><legend>1. Contact & business identity</legend><div class="form-row"><label>Your full name<input name="lead_name" required value="<?=h($name)?>"></label><label>Phone / WhatsApp<input name="lead_phone" required value="<?=h($phone)?>"></label></div><div class="form-row"><label>Email address<input type="email" name="lead_email" value="<?=h($email)?>"></label><label>Business / organization name<input name="business_name" required value="<?=h($business)?>"></label></div><div class="form-row"><label>Your role in the business<input name="role" placeholder="Owner, manager, operations lead, accountant..."></label><label>Business location<input name="location" placeholder="City, state, country"></label></div><div class="form-row"><label>Industry / business type<input name="industry" placeholder="Retail, school, clinic, restaurant, POS agency..."></label><label>How long has the business been operating?<select name="years_active"><option value="">Select one</option><option>Less than 6 months</option><option>6 months - 1 year</option><option>1 - 3 years</option><option>3 - 5 years</option><option>Over 5 years</option></select></label></div><div class="form-row"><label>Number of staff/team members<input name="staff_count" placeholder="e.g. 5"></label><label>Number of branches/locations<input name="branches" placeholder="e.g. 1"></label></div></fieldset>
<fieldset><legend>2. Current records & tools</legend><label>What tools do you currently use for records? <textarea name="current_tools" placeholder="Excel, Google Sheets, notebooks, POS reports, WhatsApp, accounting app, paper files..."></textarea></label><label>What records do you currently keep? <textarea name="records_kept" placeholder="Sales, expenses, stock, customers, staff tasks, debtors, payments, attendance..."></textarea></label><div class="form-row"><label>Where are your records stored?<select name="record_location"><option value="">Select one</option><option>Mostly paper/notebooks</option><option>Excel files</option><option>Google Sheets</option><option>POS/app exports</option><option>Mixed across many places</option><option>We do not keep proper records yet</option></select></label><label>How often are records updated?<select name="record_frequency"><option value="">Select one</option><option>Daily</option><option>Weekly</option><option>Monthly</option><option>Only when needed</option><option>Not consistent</option></select></label></div><label>How clean/complete is your current data?<select name="data_quality"><option value="">Select one</option><option>Clean and organized</option><option>Usable but scattered</option><option>Messy and inconsistent</option><option>Mostly incomplete</option><option>Not sure</option></select></label></fieldset>
<fieldset><legend>3. Sales, customers & operations</legend><label>Main products/services you sell <textarea name="products_services"></textarea></label><label>Sales/customer channels <textarea name="sales_channels" placeholder="Walk-in, WhatsApp, Instagram, website, referrals, agents, field staff..."></textarea></label><div class="form-row"><label>Approximate monthly transactions/orders/customers<input name="monthly_transactions" placeholder="e.g. 300 sales/month"></label><label>Do you have customer contact data?<select name="customer_data_available"><option value="">Select one</option><option>Yes, well organized</option><option>Yes, but scattered</option><option>Some only</option><option>No</option></select></label></div><label>How do you currently follow up customers/leads?<textarea name="customer_followup_method" placeholder="Calls, WhatsApp manually, SMS, email, no system..."></textarea></label><label>Where do you lose time or miss follow-ups?<textarea name="missed_followups"></textarea></label></fieldset>
<fieldset><legend>4. Reporting & KPI needs</legend><label>What reports do you currently prepare or review?<textarea name="current_reports" placeholder="Daily sales, monthly revenue, staff report, stock report, debtor list..."></textarea></label><label>What KPIs/numbers do you currently track?<textarea name="kpis_tracked" placeholder="Sales, revenue, profit, customers, expenses, stock, staff performance..."></textarea></label><label>What business goals should the Starter audit support?<textarea name="top_business_goals" placeholder="Increase sales, reduce manual work, understand profit, improve follow-up, track staff..."></textarea></label><label>Biggest reporting/data pain right now<textarea name="biggest_reporting_pain" required></textarea></label><div class="form-row"><label>Who will use the dashboard/report?<input name="dashboard_users" placeholder="Owner, manager, accountant, sales team..."></label><label>How often do you want to review it?<select name="dashboard_frequency"><option value="">Select one</option><option>Daily</option><option>Weekly</option><option>Monthly</option><option>Only during review meetings</option></select></label></div><label>Preferred dashboard/reporting format<select name="preferred_dashboard_format"><option value="">Select one</option><option>Google Sheets</option><option>Excel</option><option>Looker Studio / online dashboard</option><option>PDF report</option><option>Recommend the best option for us</option></select></label></fieldset>
<fieldset><legend>5. Data cleanup & audit readiness</legend><label>What data formats can you provide?<textarea name="data_formats_available" placeholder="Excel/CSV, Google Sheet, PDF report, screenshots, POS export, handwritten records..."></textarea></label><label>How should Lynxcom review your records?<select name="access_method"><option value="">Select one</option><option>I will upload/export files</option><option>I will share a Google Sheet</option><option>I need help preparing the data first</option><option>I only have screenshots/photos</option><option>Not sure yet</option></select></label><label>Are you ready to provide sample data for the audit?<select name="sample_data_ready"><option value="">Select one</option><option>Yes, immediately</option><option>Within 24 hours</option><option>Within 2-3 days</option><option>I need guidance first</option></select></label><p class="form-warning">Do not share passwords, OTPs, card details, private customer secrets, or login credentials.</p></fieldset>
<fieldset><legend>6. Automation opportunities</legend><label>Which repetitive tasks consume the most time?<textarea name="repetitive_tasks" placeholder="Follow-up messages, report preparation, staff reminders, payment chasing, data entry..."></textarea></label><label>Payment tracking situation<textarea name="payment_tracking" placeholder="How do you track paid, unpaid, part-payment, debtors, bank/POS payments?"></textarea></label><label>Debtor/customer balance tracking<textarea name="debtor_tracking"></textarea></label><label>Inventory/stock tracking<textarea name="inventory_tracking"></textarea></label><label>Staff/task/performance tracking<textarea name="staff_tracking"></textarea></label><label>Top automation priorities<select name="automation_priorities"><option value="">Select one</option><option>Customer follow-up reminders</option><option>Sales/report automation</option><option>Inventory/payment alerts</option><option>Staff/task tracking</option><option>Data cleanup and dashboard first</option><option>Recommend after audit</option></select></label></fieldset>
<fieldset><legend>7. Scope, budget & next step</legend><label>What will make this Starter audit successful for you?<textarea name="success_definition" required></textarea></label><div class="form-row"><label>Starter budget confirmation<select name="budget_confirmed" required><option value="">Select one</option><option>I understand Starter is ₦75k–₦150k</option><option>I need a final quote after review</option><option>I may need a higher package if required</option></select></label><label>Preferred timeline<select name="timeline"><option value="">Select one</option><option>This week</option><option>Next week</option><option>This month</option><option>Still planning</option></select></label></div><div class="form-row"><label>Who approves payment/project decisions?<input name="decision_maker"></label><label>Will your team need training?<select name="training_needed"><option value="">Select one</option><option>Yes</option><option>No</option><option>Maybe later</option></select></label></div><label>Privacy/data consent<select name="privacy_consent" required><option value="">Select one</option><option>I agree Lynxcom may review submitted business records only for this audit</option><option>I need clarification before sharing records</option></select></label><label>Any extra context we should know?<textarea name="extra_notes"></textarea></label></fieldset>
<button class="btn primary wide premium-submit">Submit Starter intake</button>
</form></div></section></main><footer class="footer wrap"><div><strong>Lynxcom Analytics</strong><p>Business dashboards, reporting and workflow automation.</p></div><div class="footer-links"><a href="/">Home</a><a href="blog.php">Blog</a><a href="support.php">Support</a></div></footer><script src="assets/script.js?v=starter-intake-20260825"></script></body></html>
