<?php
function h($v){ return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
$status = $_GET['status'] ?? '';
$form = $_GET['form'] ?? 'admissions';
$sid = $_GET['sid'] ?? '';
$forms = ['admissions'=>'Admissions', 'billing'=>'Invoice / Fee Billing', 'fee'=>'Fee Payment', 'followup'=>'Parent Follow-up', 'student'=>'Student Record', 'staff'=>'Staff Record', 'boarding'=>'Boarding / Hostel', 'results'=>'Academic Result', 'expense'=>'Expense', 'attendance'=>'Attendance'];
$classes = ['Primary 1','Primary 2','Primary 3','Primary 4','Primary 5','Primary 6','JSS 1','JSS 2','JSS 3','SS 1','SS 2','SS 3'];
$terms = ['2025/2026 First Term','2025/2026 Second Term','2025/2026 Third Term','2024/2025 First Term','2024/2025 Second Term','2024/2025 Third Term','2023/2024 First Term','2023/2024 Second Term','2023/2024 Third Term'];
$students = [];
$classExpected = [];
$dataFile = __DIR__ . '/data/dashboard-data.json';
if(is_file($dataFile)){
  $data = json_decode(file_get_contents($dataFile), true);
  foreach(($data['charts']['fee_by_class'] ?? []) as $feeRow){
    $className = trim($feeRow['class'] ?? '');
    $studentCount = 0;
    foreach(($data['charts']['enrollment_by_class'] ?? []) as $enrollRow){ if(($enrollRow['label'] ?? '') === $className) $studentCount = (int)($enrollRow['value'] ?? 0); }
    if($className && $studentCount > 0) $classExpected[$className] = round(((float)($feeRow['billed'] ?? 0)) / $studentCount);
  }
  foreach(($data['debtors'] ?? []) as $d){
    $id = trim($d['student_id'] ?? '');
    if($id && !isset($students[$id])){
      $students[$id] = [
        'id'=>$id,
        'name'=>$d['student_name'] ?? '',
        'class'=>$d['class'] ?? '',
        'gender'=>'',
        'guardian'=>$d['guardian_name'] ?? '',
        'phone'=>$d['guardian_phone'] ?? '',
        'section'=>$d['section'] ?? '',
        'expected_amount'=>$d['amount_billed'] ?? ($classExpected[$d['class'] ?? ''] ?? '')
      ];
    }
  }
}
$admissionCsv = __DIR__ . '/submissions/Admissions.csv';
if(is_file($admissionCsv) && ($fp=fopen($admissionCsv,'r'))){
  while(($row=fgetcsv($fp))!==false){
    // New format: timestamp, student_id, student_name, class, gender, guardian, phone, source, stage, status, notes
    if(count($row)>=10){
      $id=trim($row[1] ?? ''); $stage=trim($row[8] ?? '');
      if($id && strcasecmp($stage,'Admitted')===0){
        $students[$id]=['id'=>$id,'name'=>$row[2]??'','class'=>$row[3]??'','gender'=>$row[4]??'','guardian'=>$row[5]??'','phone'=>$row[6]??'','section'=>str_starts_with(($row[3]??''),'Primary')?'Primary':'Secondary Boarding','expected_amount'=>$classExpected[$row[3]??''] ?? ''];
      }
    }
  }
  fclose($fp);
}
ksort($students);
function class_options($classes,$selected='') { foreach($classes as $c){ echo '<option value="'.h($c).'"'.($selected===$c?' selected':'').'>'.h($c).'</option>'; } }
function term_options($terms,$selected='') { foreach($terms as $t){ echo '<option value="'.h($t).'"'.($selected===$t?' selected':'').'>'.h($t).'</option>'; } }
function student_options($students) { foreach($students as $s){ echo '<option value="'.h($s['id']).'" data-name="'.h($s['name']).'" data-class="'.h($s['class']).'" data-gender="'.h($s['gender']).'" data-guardian="'.h($s['guardian']).'" data-phone="'.h($s['phone']).'" data-section="'.h($s['section']).'" data-expected="'.h($s['expected_amount'] ?? '').'">'.h($s['id'].' — '.$s['name'].' ('.$s['class'].')').'</option>'; } }
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>School Data Entry Portal | Crestfield Demo</title><link rel="stylesheet" href="assets/styles.css?v=starter-role-access-20260831"></head>
<body><header class="report-top"><div class="report-brand"><a class="sample-brand-logo" href="../" aria-label="LynxCom Analytics home"><img src="../assets/lynxcom-logo.svg" alt="LynxCom Analytics logo"></a><div><strong>LynxCom Analytics</strong><small>Starter online form → Google Sheet backend sample</small></div></div><div class="report-meta"><b>Crestfield Model Academy</b><span>Data Entry Portal</span><a class="portal-link" href="login.html">Role Login</a><a class="portal-link" href="academic.html">Academic Dashboard</a><a class="portal-link" href="index.html">Back to Dashboard</a></div></header>
<main class="portal-page"><section class="report-title-card"><div><p class="eyebrow">Starter sample workflow</p><h1>School Data Entry Portal</h1><p>Staff use controlled forms for admissions, billing, payments, debtor follow-up, student records, staff, boarding, results, expenses and attendance. Linked dropdowns reduce typo errors and keep records consistent.</p><div class="hero-actions"><a class="report-btn secondary" href="academic.html">View Academic Dashboard</a><a class="report-btn" href="index.html">View Admin Dashboard</a></div></div><aside><span>Integrity rule</span><strong>Admissions first</strong><small>A student must be admitted and have a Student ID before Student Record or Fee Payment entries can be saved.</small></aside></section>
<div class="portal-shell"><aside class="portal-side"><p class="eyebrow">Form modules</p><h2>Capture daily school records</h2><p>This version demonstrates referential integrity: dropdowns, linked fields, and Student ID validation.</p><ul><li>Class and term fields use controlled lists</li><li>Student ID auto-fills linked student details</li><li>Student records cannot bypass admissions</li><li>Billing, payments, boarding, results and follow-up are linked to admitted students</li></ul><div class="portal-tabs"><?php foreach($forms as $key=>$label): ?><button type="button" data-form="<?=h($key)?>" class="<?=$form===$key?'active':''?>"><?=h($label)?></button><?php endforeach; ?></div></aside><section>
<?php if($status==='success'): ?><div class="success-box">Submission saved successfully for the sample portal.</div><?php elseif($status==='admitted'): ?><div class="success-box">Student admitted successfully. Assigned Student ID: <strong><?=h($sid)?></strong>. This ID can now be used in Student Record and Fee Payment forms.</div><?php elseif($status==='not_admitted'): ?><div class="error-box">Student Record/Fee Payment cannot be saved. Select a valid admitted Student ID first.</div><?php elseif($status==='class_mismatch'): ?><div class="error-box">Selected Student ID does not belong to the selected class. Choose the class first, then pick a matching Student ID.</div><?php elseif($status==='error'): ?><div class="error-box">Submission could not be saved. Please check the form and try again.</div><?php endif; ?>
<div class="portal-note"><strong>Demo note:</strong> This portal now uses controlled dropdowns for Class, Term and Student ID. In a live client system, these reference lists would come from the master Google Sheet tabs.</div>

<article class="form-panel <?=$form==='admissions'?'active':''?>" id="form-admissions"><h2>Admissions Enquiry Form</h2><p>Capture admission enquiries. When Stage is <strong>Admitted</strong>, the system assigns a Student ID.</p><form class="portal-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Admissions"><label>Student Name<input name="student_name" required></label><label>Applying Class<select name="applying_class" required><option value="">Select class</option><?php class_options($classes); ?></select></label><label>Gender<select name="gender" required><option value="">Select gender</option><option>Male</option><option>Female</option></select></label><label>Parent/Guardian<input name="guardian" required></label><label>Phone<input name="phone" required></label><label>Source<select name="source"><option>Walk-in</option><option>Facebook</option><option>Referral</option><option>WhatsApp</option><option>Website</option></select></label><label>Stage<select name="stage"><option>New Enquiry</option><option>Form Purchased</option><option>Entrance Test</option><option>Admitted</option><option>Not Converted</option></select></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit admission enquiry</button></form></article>

<article class="form-panel <?=$form==='fee'?'active':''?>" id="form-fee"><h2>Fee Payment Form</h2><p>Select Class first; Student ID list will show only admitted students in that class.</p><form class="portal-form linked-student-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Fee_Payments"><label class="full">Class<select name="class" class="class-first-select" required><option value="">Select class first</option><?php class_options($classes); ?></select></label><label class="full">Student ID<select name="student_id" class="student-id-select" required disabled><option value="">Select class first to load student IDs</option><?php student_options($students); ?></select></label><p class="integrity-help full">Only students admitted under the selected class will appear here.</p><label>Student Name<input name="student_name" readonly required></label><label>Gender<select name="gender" readonly><option value="">From Student ID</option><option>Male</option><option>Female</option></select></label><label>Parent/Guardian<input name="guardian" readonly></label><label>Phone<input name="phone" readonly></label><label>Term<select name="term" required><option value="">Select term</option><?php term_options($terms); ?></select></label><label>Expected Amount<input name="expected_amount" type="number" min="0" readonly required placeholder="Generated from Student ID"></label><label>Amount Paid<input name="amount_paid" type="number" min="0" required></label><label>Payment Method<select name="payment_method"><option>Cash</option><option>Transfer</option><option>POS</option><option>Bank Deposit</option></select></label><label>Receipt No<input name="receipt_no"></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit fee payment</button></form></article>


<article class="form-panel <?=$form==='billing'?'active':''?>" id="form-billing"><h2>Invoice / Fee Billing Form</h2><p>Create the amount a student is expected to pay for a selected term. Class filters the Student ID list.</p><form class="portal-form linked-student-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Fee_Billing"><label class="full">Class<select name="class" class="class-first-select" required><option value="">Select class first</option><?php class_options($classes); ?></select></label><label class="full">Student ID<select name="student_id" class="student-id-select" required disabled><option value="">Select class first to load student IDs</option><?php student_options($students); ?></select></label><p class="integrity-help full">Only admitted students in the selected class appear here.</p><label>Student Name<input name="student_name" readonly required></label><label>Term<select name="term" required><option value="">Select term</option><?php term_options($terms); ?></select></label><label>Fee Category<select name="fee_category" required><option>School Fees</option><option>Boarding Fees</option><option>Exam Fees</option><option>Books / Materials</option><option>Transport</option><option>Other</option></select></label><label>Expected Amount<input name="expected_amount" type="number" min="0" required></label><label>Discount / Scholarship<input name="discount" type="number" min="0" value="0"></label><label>Due Date<input name="due_date" type="date"></label><label>Billing Status<select name="billing_status"><option>Unpaid</option><option>Part Paid</option><option>Paid</option><option>Waived</option></select></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit fee billing</button></form></article>

<article class="form-panel <?=$form==='followup'?'active':''?>" id="form-followup"><h2>Parent Follow-up / Debtor Action Form</h2><p>Track calls, WhatsApp messages, promises to pay and escalation for fee recovery.</p><form class="portal-form linked-student-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Parent_Followup"><label class="full">Class<select name="class" class="class-first-select" required><option value="">Select class first</option><?php class_options($classes); ?></select></label><label class="full">Student ID<select name="student_id" class="student-id-select" required disabled><option value="">Select class first to load student IDs</option><?php student_options($students); ?></select></label><p class="integrity-help full">Select a student to auto-fill parent details.</p><label>Student Name<input name="student_name" readonly required></label><label>Parent/Guardian<input name="guardian" readonly required></label><label>Phone<input name="phone" readonly required></label><label>Outstanding Amount<input name="outstanding_amount" type="number" min="0"></label><label>Follow-up Date<input name="followup_date" type="date" required></label><label>Contact Method<select name="contact_method"><option>Call</option><option>WhatsApp</option><option>SMS</option><option>Visit</option></select></label><label>Promise-to-pay Date<input name="promise_date" type="date"></label><label>Owner<select name="owner"><option>Bursar</option><option>Admin Officer</option><option>School Owner</option><option>Class Teacher</option></select></label><label>Status<select name="followup_status"><option>Pending</option><option>Promised</option><option>Paid</option><option>Escalated</option><option>No Response</option></select></label><label class="full">Parent Response / Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit follow-up action</button></form></article>

<article class="form-panel <?=$form==='staff'?'active':''?>" id="form-staff"><h2>Staff Record Form</h2><p>Capture teacher and non-teaching staff records for operations and payroll planning.</p><form class="portal-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Staff"><label>Staff ID<input name="staff_id" placeholder="Auto/manual ID"></label><label>Staff Name<input name="staff_name" required></label><label>Gender<select name="gender" required><option value="">Select gender</option><option>Male</option><option>Female</option></select></label><label>Role<input name="role" required></label><label>Department<select name="department"><option>Primary</option><option>Secondary</option><option>Administration</option><option>Boarding</option><option>Security</option><option>Kitchen</option></select></label><label>Assigned Class<select name="assigned_class"><option value="">Not class-based</option><?php class_options($classes); ?></select></label><label>Phone<input name="phone"></label><label>Date Joined<input name="date_joined" type="date"></label><label>Employment Status<select name="employment_status"><option>Active</option><option>On Leave</option><option>Exited</option></select></label><label>Salary Category<select name="salary_category"><option>Teaching Staff</option><option>Admin Staff</option><option>Support Staff</option><option>Contract</option></select></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit staff record</button></form></article>

<article class="form-panel <?=$form==='boarding'?'active':''?>" id="form-boarding"><h2>Boarding / Hostel Record Form</h2><p>Assign boarding students to hostel, dormitory and bed space.</p><form class="portal-form linked-student-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Boarding"><label class="full">Class<select name="class" class="class-first-select" required><option value="">Select class first</option><?php class_options($classes); ?></select></label><label class="full">Student ID<select name="student_id" class="student-id-select" required disabled><option value="">Select class first to load student IDs</option><?php student_options($students); ?></select></label><p class="integrity-help full">Only admitted students in the selected class can be assigned to hostel records.</p><label>Student Name<input name="student_name" readonly required></label><label>Hostel / House<select name="hostel" required><option>Blue House Hostel</option><option>Green House Hostel</option><option>Gold House Hostel</option><option>Red House Hostel</option></select></label><label>Room / Dormitory<input name="room" required></label><label>Bed Space<input name="bed_space" required></label><label>Boarding Status<select name="boarding_status"><option>Active Boarder</option><option>Day Student</option><option>Weekend Leave</option><option>Exited Boarding</option></select></label><label>Emergency Contact<input name="emergency_contact"></label><label class="full">Medical Note<textarea name="medical_note"></textarea></label><button class="portal-submit">Submit boarding record</button></form></article>

<article class="form-panel <?=$form==='results'?'active':''?>" id="form-results"><h2>Academic Result / Assessment Form</h2><p>Record subject scores by term. Student ID is filtered by selected class.</p><form class="portal-form linked-student-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Results"><label>Term<select name="term" required><option value="">Select term</option><?php term_options($terms); ?></select></label><label>Class<select name="class" class="class-first-select" required><option value="">Select class first</option><?php class_options($classes); ?></select></label><label class="full">Student ID<select name="student_id" class="student-id-select" required disabled><option value="">Select class first to load student IDs</option><?php student_options($students); ?></select></label><p class="integrity-help full">Select class first to avoid entering scores under the wrong student.</p><label>Student Name<input name="student_name" readonly required></label><label>Subject<select name="subject" required><option>Mathematics</option><option>English Language</option><option>Basic Science</option><option>Social Studies</option><option>Computer Studies</option><option>Business Studies</option><option>Biology</option><option>Chemistry</option><option>Physics</option><option>Economics</option></select></label><label>CA Score<input name="ca_score" type="number" min="0" max="40" required></label><label>Exam Score<input name="exam_score" type="number" min="0" max="60" required></label><label>Teacher<input name="teacher"></label><label class="full">Remarks<textarea name="remarks"></textarea></label><button class="portal-submit">Submit result record</button></form></article>

<article class="form-panel <?=$form==='expense'?'active':''?>" id="form-expense"><h2>Expense Form</h2><p>Record school expenses for management review.</p><form class="portal-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Expenses"><label>Expense Date<input name="expense_date" type="date" required></label><label>Category<select name="category" required><option value="">Select category</option><option>Staff Salaries</option><option>Feeding</option><option>Utilities</option><option>Maintenance</option><option>Learning Materials</option><option>Transport</option><option>Other</option></select></label><label class="full">Description<input name="description" required></label><label>Amount<input name="amount" type="number" min="0" required></label><label>Paid By<input name="paid_by"></label><label>Payment Method<select name="payment_method"><option>Cash</option><option>Transfer</option><option>POS</option></select></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit expense</button></form></article>

<article class="form-panel <?=$form==='attendance'?'active':''?>" id="form-attendance"><h2>Attendance Form</h2><p>Record class attendance summary using controlled class and term lists.</p><form class="portal-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Attendance"><label>Date<input name="date" type="date" required></label><label>Term<select name="term" required><option value="">Select term</option><?php term_options($terms); ?></select></label><label>Class<select name="class" required><option value="">Select class</option><?php class_options($classes); ?></select></label><label>Gender<select name="gender"><option value="">Mixed / Not split</option><option>Male</option><option>Female</option></select></label><label>Section<select name="section"><option>Primary</option><option>Secondary Boarding</option></select></label><label>Total Students<input name="total_students" type="number" min="0" required></label><label>Present<input name="present" type="number" min="0" required></label><label>Absent<input name="absent" type="number" min="0" required></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit attendance</button></form></article>

<article class="form-panel <?=$form==='student'?'active':''?>" id="form-student"><h2>Student Record Form</h2><p>Select Class first; then choose an admitted Student ID from that class. Linked fields auto-fill.</p><form class="portal-form linked-student-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Students"><label class="full">Class<select name="class" class="class-first-select" required><option value="">Select class first</option><?php class_options($classes); ?></select></label><label class="full">Student ID<select name="student_id" class="student-id-select" required disabled><option value="">Select class first to load student IDs</option><?php student_options($students); ?></select></label><p class="integrity-help full">This prevents staff from choosing the wrong student or mistyping Student IDs.</p><label>Student Name<input name="student_name" readonly required></label><label>Gender<select name="gender" required><option value="">From Student ID</option><option>Male</option><option>Female</option></select></label><label>Section<select name="section"><option>Primary</option><option>Secondary Boarding</option></select></label><label>Parent/Guardian<input name="guardian" readonly required></label><label>Phone<input name="phone" readonly required></label><label>Status<select name="status"><option>Active</option><option>Transferred</option><option>Graduated</option><option>Inactive</option></select></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit student record</button></form></article>
</section></div></main><footer class="report-footer"><strong>LynxCom Analytics</strong><span>Starter sample: controlled forms feeding structured backend records.</span></footer><script src="assets/roles.js?v=starter-role-access-20260831"></script><script>window.LynxRole?.init('portal');
document.querySelectorAll('[data-form]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-form]').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.form-panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');document.getElementById('form-'+btn.dataset.form).classList.add('active');history.replaceState(null,'','?form='+btn.dataset.form);});
function setField(form,name,value){const el=form.querySelector(`[name="${name}"]`); if(!el) return; el.value=value||''; el.dispatchEvent(new Event('change',{bubbles:true}));}
function clearLinkedStudentFields(form){['student_name','gender','guardian','phone','section','expected_amount'].forEach(n=>setField(form,n,''));}
function filterStudentIds(form){const classSel=form.querySelector('select[name="class"]'); const idSel=form.querySelector('.student-id-select'); if(!classSel||!idSel) return; const selectedClass=classSel.value; idSel.value=''; clearLinkedStudentFields(form); let shown=0; Array.from(idSel.options).forEach((opt,i)=>{if(i===0){opt.hidden=false; opt.disabled=false; opt.textContent=selectedClass?'Select admitted student ID':'Select class first to load student IDs'; return;} const match=!!selectedClass && opt.dataset.class===selectedClass; opt.hidden=!match; opt.disabled=!match; if(match) shown++;}); idSel.disabled=!selectedClass || shown===0; const help=form.querySelector('.integrity-help'); if(help){help.textContent=!selectedClass?'Select a class first; the Student ID list will load after that.':(shown?`${shown} admitted student ID(s) available for ${selectedClass}.`:`No admitted Student ID found for ${selectedClass}. Admit the student first.`);} }
document.querySelectorAll('.linked-student-form').forEach(form=>{filterStudentIds(form); const classSel=form.querySelector('select[name="class"]'); classSel?.addEventListener('change',()=>{const section=form.querySelector('[name="section"]'); if(section && classSel.value){section.value=classSel.value.startsWith('Primary')?'Primary':'Secondary Boarding';} filterStudentIds(form);});});
document.querySelectorAll('.student-id-select').forEach(sel=>sel.addEventListener('change',()=>{const opt=sel.selectedOptions[0]; const form=sel.closest('form'); if(!opt||!opt.value){clearLinkedStudentFields(form); return;} setField(form,'student_name',opt.dataset.name); setField(form,'gender',opt.dataset.gender); setField(form,'guardian',opt.dataset.guardian); setField(form,'phone',opt.dataset.phone); setField(form,'section',opt.dataset.section || (String(opt.dataset.class||'').startsWith('Primary')?'Primary':'Secondary Boarding')); setField(form,'expected_amount',opt.dataset.expected); }));
document.querySelectorAll('form:not(.linked-student-form) select[name="class"]').forEach(sel=>sel.addEventListener('change',()=>{const form=sel.closest('form'); const section=form?.querySelector('[name="section"]'); if(section && sel.value){section.value=sel.value.startsWith('Primary')?'Primary':'Secondary Boarding';}}));


</script></body></html>
