<?php
function h($v){ return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
$status = $_GET['status'] ?? '';
$form = $_GET['form'] ?? 'admissions';
$sid = $_GET['sid'] ?? '';
$forms = ['admissions'=>'Admissions', 'fee'=>'Fee Payment', 'expense'=>'Expense', 'attendance'=>'Attendance', 'student'=>'Student Record'];
$classes = ['Primary 1','Primary 2','Primary 3','Primary 4','Primary 5','Primary 6','JSS 1','JSS 2','JSS 3','SS 1','SS 2','SS 3'];
$terms = ['2025/2026 First Term','2025/2026 Second Term','2025/2026 Third Term','2024/2025 First Term','2024/2025 Second Term','2024/2025 Third Term','2023/2024 First Term','2023/2024 Second Term','2023/2024 Third Term'];
$students = [];
$dataFile = __DIR__ . '/data/dashboard-data.json';
if(is_file($dataFile)){
  $data = json_decode(file_get_contents($dataFile), true);
  foreach(($data['debtors'] ?? []) as $d){
    $id = trim($d['student_id'] ?? '');
    if($id && !isset($students[$id])){
      $students[$id] = [
        'id'=>$id,
        'name'=>$d['student_name'] ?? '',
        'class'=>$d['class'] ?? '',
        'gender'=>'',
        'guardian'=>$d['guardian_name'] ?? '',
        'phone'=>$d['guardian_phone'] ?? '',
        'section'=>$d['section'] ?? ''
      ];
    }
  }
}
$admissionCsv = __DIR__ . '/submissions/Admissions.csv';
if(is_file($admissionCsv) && ($fp=fopen($admissionCsv,'r'))){
  while(($row=fgetcsv($fp))!==false){
    // New format: timestamp, student_id, student_name, class, gender, guardian, phone, source, stage, status, notes
    if(count($row)>=10){
      $id=trim($row[1] ?? ''); $stage=trim($row[8] ?? '');
      if($id && strcasecmp($stage,'Admitted')===0){
        $students[$id]=['id'=>$id,'name'=>$row[2]??'','class'=>$row[3]??'','gender'=>$row[4]??'','guardian'=>$row[5]??'','phone'=>$row[6]??'','section'=>str_starts_with(($row[3]??''),'Primary')?'Primary':'Secondary Boarding'];
      }
    }
  }
  fclose($fp);
}
ksort($students);
function class_options($classes,$selected='') { foreach($classes as $c){ echo '<option value="'.h($c).'"'.($selected===$c?' selected':'').'>'.h($c).'</option>'; } }
function term_options($terms,$selected='') { foreach($terms as $t){ echo '<option value="'.h($t).'"'.($selected===$t?' selected':'').'>'.h($t).'</option>'; } }
function student_options($students) { foreach($students as $s){ echo '<option value="'.h($s['id']).'" data-name="'.h($s['name']).'" data-class="'.h($s['class']).'" data-gender="'.h($s['gender']).'" data-guardian="'.h($s['guardian']).'" data-phone="'.h($s['phone']).'" data-section="'.h($s['section']).'">'.h($s['id'].' — '.$s['name'].' ('.$s['class'].')').'</option>'; } }
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>School Data Entry Portal | Crestfield Demo</title><link rel="stylesheet" href="assets/styles.css?v=referential-integrity-20260831"></head>
<body><header class="report-top"><div class="report-brand"><a class="sample-brand-logo" href="../" aria-label="LynxCom Analytics home"><img src="../assets/lynxcom-logo.svg" alt="LynxCom Analytics logo"></a><div><strong>LynxCom Analytics</strong><small>Starter online form → Google Sheet backend sample</small></div></div><div class="report-meta"><b>Crestfield Model Academy</b><span>Data Entry Portal</span><a class="portal-link" href="index.html">Back to Dashboard</a></div></header>
<main class="portal-page"><section class="report-title-card"><div><p class="eyebrow">Starter sample workflow</p><h1>School Data Entry Portal</h1><p>Staff use controlled dropdowns for class, term and Student ID. Student records and fee payments are linked to admitted students to prevent typo errors and duplicate records.</p></div><aside><span>Integrity rule</span><strong>Admissions first</strong><small>A student must be admitted and have a Student ID before Student Record or Fee Payment entries can be saved.</small></aside></section>
<div class="portal-shell"><aside class="portal-side"><p class="eyebrow">Form modules</p><h2>Capture daily school records</h2><p>This version demonstrates referential integrity: dropdowns, linked fields, and Student ID validation.</p><ul><li>Class and term fields use controlled lists</li><li>Student ID auto-fills linked student details</li><li>Student records cannot bypass admissions</li></ul><div class="portal-tabs"><?php foreach($forms as $key=>$label): ?><button type="button" data-form="<?=h($key)?>" class="<?=$form===$key?'active':''?>"><?=h($label)?></button><?php endforeach; ?></div></aside><section>
<?php if($status==='success'): ?><div class="success-box">Submission saved successfully for the sample portal.</div><?php elseif($status==='admitted'): ?><div class="success-box">Student admitted successfully. Assigned Student ID: <strong><?=h($sid)?></strong>. This ID can now be used in Student Record and Fee Payment forms.</div><?php elseif($status==='not_admitted'): ?><div class="error-box">Student Record/Fee Payment cannot be saved. Select a valid admitted Student ID first.</div><?php elseif($status==='error'): ?><div class="error-box">Submission could not be saved. Please check the form and try again.</div><?php endif; ?>
<div class="portal-note"><strong>Demo note:</strong> This portal now uses controlled dropdowns for Class, Term and Student ID. In a live client system, these reference lists would come from the master Google Sheet tabs.</div>

<article class="form-panel <?=$form==='admissions'?'active':''?>" id="form-admissions"><h2>Admissions Enquiry Form</h2><p>Capture admission enquiries. When Stage is <strong>Admitted</strong>, the system assigns a Student ID.</p><form class="portal-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Admissions"><label>Student Name<input name="student_name" required></label><label>Applying Class<select name="applying_class" required><option value="">Select class</option><?php class_options($classes); ?></select></label><label>Gender<select name="gender" required><option value="">Select gender</option><option>Male</option><option>Female</option></select></label><label>Parent/Guardian<input name="guardian" required></label><label>Phone<input name="phone" required></label><label>Source<select name="source"><option>Walk-in</option><option>Facebook</option><option>Referral</option><option>WhatsApp</option><option>Website</option></select></label><label>Stage<select name="stage"><option>New Enquiry</option><option>Form Purchased</option><option>Entrance Test</option><option>Admitted</option><option>Not Converted</option></select></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit admission enquiry</button></form></article>

<article class="form-panel <?=$form==='fee'?'active':''?>" id="form-fee"><h2>Fee Payment Form</h2><p>Select Student ID first; linked student details auto-fill to prevent typo errors.</p><form class="portal-form linked-student-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Fee_Payments"><label class="full">Student ID<select name="student_id" class="student-id-select" required><option value="">Select admitted student ID</option><?php student_options($students); ?></select></label><label>Student Name<input name="student_name" readonly required></label><label>Gender<select name="gender" readonly><option value="">From Student ID</option><option>Male</option><option>Female</option></select></label><label>Class<select name="class" required><option value="">Select class</option><?php class_options($classes); ?></select></label><label>Parent/Guardian<input name="guardian" readonly></label><label>Phone<input name="phone" readonly></label><label>Term<select name="term" required><option value="">Select term</option><?php term_options($terms); ?></select></label><label>Amount Paid<input name="amount_paid" type="number" min="0" required></label><label>Payment Method<select name="payment_method"><option>Cash</option><option>Transfer</option><option>POS</option><option>Bank Deposit</option></select></label><label>Receipt No<input name="receipt_no"></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit fee payment</button></form></article>

<article class="form-panel <?=$form==='expense'?'active':''?>" id="form-expense"><h2>Expense Form</h2><p>Record school expenses for management review.</p><form class="portal-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Expenses"><label>Expense Date<input name="expense_date" type="date" required></label><label>Category<select name="category" required><option value="">Select category</option><option>Staff Salaries</option><option>Feeding</option><option>Utilities</option><option>Maintenance</option><option>Learning Materials</option><option>Transport</option><option>Other</option></select></label><label class="full">Description<input name="description" required></label><label>Amount<input name="amount" type="number" min="0" required></label><label>Paid By<input name="paid_by"></label><label>Payment Method<select name="payment_method"><option>Cash</option><option>Transfer</option><option>POS</option></select></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit expense</button></form></article>

<article class="form-panel <?=$form==='attendance'?'active':''?>" id="form-attendance"><h2>Attendance Form</h2><p>Record class attendance summary using controlled class and term lists.</p><form class="portal-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Attendance"><label>Date<input name="date" type="date" required></label><label>Term<select name="term" required><option value="">Select term</option><?php term_options($terms); ?></select></label><label>Class<select name="class" required><option value="">Select class</option><?php class_options($classes); ?></select></label><label>Gender<select name="gender"><option value="">Mixed / Not split</option><option>Male</option><option>Female</option></select></label><label>Section<select name="section"><option>Primary</option><option>Secondary Boarding</option></select></label><label>Total Students<input name="total_students" type="number" min="0" required></label><label>Present<input name="present" type="number" min="0" required></label><label>Absent<input name="absent" type="number" min="0" required></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit attendance</button></form></article>

<article class="form-panel <?=$form==='student'?'active':''?>" id="form-student"><h2>Student Record Form</h2><p>Student ID must already exist from Admissions. Selecting the ID fills the linked fields.</p><form class="portal-form linked-student-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Students"><label class="full">Student ID<select name="student_id" class="student-id-select" required><option value="">Select admitted student ID</option><?php student_options($students); ?></select></label><label>Student Name<input name="student_name" readonly required></label><label>Gender<select name="gender" required><option value="">From Student ID</option><option>Male</option><option>Female</option></select></label><label>Class<select name="class" required><option value="">Select class</option><?php class_options($classes); ?></select></label><label>Section<select name="section"><option>Primary</option><option>Secondary Boarding</option></select></label><label>Parent/Guardian<input name="guardian" readonly required></label><label>Phone<input name="phone" readonly required></label><label>Status<select name="status"><option>Active</option><option>Transferred</option><option>Graduated</option><option>Inactive</option></select></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit student record</button></form></article>
</section></div></main><footer class="report-footer"><strong>LynxCom Analytics</strong><span>Starter sample: controlled forms feeding structured backend records.</span></footer><script>
document.querySelectorAll('[data-form]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-form]').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.form-panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');document.getElementById('form-'+btn.dataset.form).classList.add('active');history.replaceState(null,'','?form='+btn.dataset.form);});
function setField(form,name,value){const el=form.querySelector(`[name="${name}"]`); if(!el) return; el.value=value||''; el.dispatchEvent(new Event('change',{bubbles:true}));}
document.querySelectorAll('.student-id-select').forEach(sel=>sel.addEventListener('change',()=>{const opt=sel.selectedOptions[0]; const form=sel.closest('form'); if(!opt||!opt.value){['student_name','gender','class','guardian','phone','section'].forEach(n=>setField(form,n,'')); return;} setField(form,'student_name',opt.dataset.name); setField(form,'gender',opt.dataset.gender); setField(form,'class',opt.dataset.class); setField(form,'guardian',opt.dataset.guardian); setField(form,'phone',opt.dataset.phone); setField(form,'section',opt.dataset.section || (String(opt.dataset.class||'').startsWith('Primary')?'Primary':'Secondary Boarding'));}));
document.querySelectorAll('select[name="class"]').forEach(sel=>sel.addEventListener('change',()=>{const form=sel.closest('form'); const section=form?.querySelector('[name="section"]'); if(section && sel.value){section.value=sel.value.startsWith('Primary')?'Primary':'Secondary Boarding';}}));
</script></body></html>