<?php
$status = $_GET['status'] ?? '';
$form = $_GET['form'] ?? 'admissions';
$forms = ['admissions'=>'Admissions', 'fee'=>'Fee Payment', 'expense'=>'Expense', 'attendance'=>'Attendance', 'student'=>'Student Record'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>School Data Entry Portal | Crestfield Demo</title><link rel="stylesheet" href="assets/styles.css?v=portal-forms-20260831"></head>
<body><header class="report-top"><div class="report-brand"><a class="sample-brand-logo" href="../" aria-label="LynxCom Analytics home"><img src="../assets/lynxcom-logo.svg" alt="LynxCom Analytics logo"></a><div><strong>LynxCom Analytics</strong><small>Starter online form → Google Sheet backend sample</small></div></div><div class="report-meta"><b>Crestfield Model Academy</b><span>Data Entry Portal</span><a class="portal-link" href="index.html">Back to Dashboard</a></div></header>
<main class="portal-page"><section class="report-title-card"><div><p class="eyebrow">Starter sample workflow</p><h1>School Data Entry Portal</h1><p>Staff use simple online forms to record admissions, payments, expenses, attendance and student records. For a real client, these submissions feed the Google Sheet backend and then the dashboard is refreshed from that structured data.</p></div><aside><span>Backend model</span><strong>Forms → Google Sheet</strong><small>Safe sample: no real student/parent data.</small></aside></section>
<div class="portal-shell"><aside class="portal-side"><p class="eyebrow">Form modules</p><h2>Capture daily school records</h2><p>This is the Starter-friendly version: simple forms, structured backend tabs, and dashboard refresh on agreed schedule.</p><ul><li>No raw Excel dashboard for client view</li><li>Forms reduce entry mistakes</li><li>Google Sheet remains backend source</li></ul><div class="portal-tabs"><?php foreach($forms as $key=>$label): ?><button type="button" data-form="<?=$key?>" class="<?=$form===$key?'active':''?>"><?=$label?></button><?php endforeach; ?></div></aside><section>
<?php if($status==='success'): ?><div class="success-box">Submission saved successfully for the sample portal.</div><?php elseif($status==='error'): ?><div class="error-box">Submission could not be saved. Please check the form and try again.</div><?php endif; ?>
<div class="portal-note">Demo note: This portal is privacy-safe. Use dummy entries only. The Google Sheet backend has been created for this sample; live client deployment should connect the secure webhook.</div>

<article class="form-panel <?=$form==='admissions'?'active':''?>" id="form-admissions"><h2>Admissions Enquiry Form</h2><p>Capture new admission enquiries and follow-up stage.</p><form class="portal-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Admissions"><label>Student Name<input name="student_name" required></label><label>Applying Class<input name="applying_class" required></label><label>Gender<select name="gender" required><option value="">Select gender</option><option>Male</option><option>Female</option></select></label><label>Parent/Guardian<input name="guardian" required></label><label>Phone<input name="phone" required></label><label>Source<select name="source"><option>Walk-in</option><option>Facebook</option><option>Referral</option><option>WhatsApp</option><option>Website</option></select></label><label>Stage<select name="stage"><option>New Enquiry</option><option>Form Purchased</option><option>Entrance Test</option><option>Admitted</option><option>Not Converted</option></select></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit admission enquiry</button></form></article>

<article class="form-panel <?=$form==='fee'?'active':''?>" id="form-fee"><h2>Fee Payment Form</h2><p>Record school fee payments into the backend.</p><form class="portal-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Fee_Payments"><label>Student Name<input name="student_name" required></label><label>Student ID<input name="student_id"></label><label>Gender<select name="gender"><option value="">Select gender</option><option>Male</option><option>Female</option></select></label><label>Class<input name="class" required></label><label>Parent/Guardian<input name="guardian"></label><label>Phone<input name="phone"></label><label>Term<input name="term" required></label><label>Amount Paid<input name="amount_paid" type="number" required></label><label>Payment Method<select name="payment_method"><option>Cash</option><option>Transfer</option><option>POS</option><option>Bank Deposit</option></select></label><label>Receipt No<input name="receipt_no"></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit fee payment</button></form></article>

<article class="form-panel <?=$form==='expense'?'active':''?>" id="form-expense"><h2>Expense Form</h2><p>Record school expenses for management review.</p><form class="portal-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Expenses"><label>Expense Date<input name="expense_date" type="date" required></label><label>Category<input name="category" required></label><label class="full">Description<input name="description" required></label><label>Amount<input name="amount" type="number" required></label><label>Paid By<input name="paid_by"></label><label>Payment Method<select name="payment_method"><option>Cash</option><option>Transfer</option><option>POS</option></select></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit expense</button></form></article>

<article class="form-panel <?=$form==='attendance'?'active':''?>" id="form-attendance"><h2>Attendance Form</h2><p>Record class attendance summary.</p><form class="portal-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Attendance"><label>Date<input name="date" type="date" required></label><label>Class<input name="class" required></label><label>Gender<select name="gender"><option value="">Mixed / Not split</option><option>Male</option><option>Female</option></select></label><label>Section<select name="section"><option>Primary</option><option>Secondary Boarding</option></select></label><label>Total Students<input name="total_students" type="number" required></label><label>Present<input name="present" type="number" required></label><label>Absent<input name="absent" type="number" required></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit attendance</button></form></article>

<article class="form-panel <?=$form==='student'?'active':''?>" id="form-student"><h2>Student Record Form</h2><p>Add/update a student record.</p><form class="portal-form" method="post" action="submit.php"><input type="hidden" name="form_type" value="Students"><label>Student Name<input name="student_name" required></label><label>Student ID<input name="student_id"></label><label>Class<input name="class" required></label><label>Gender<select name="gender" required><option value="">Select gender</option><option>Male</option><option>Female</option></select></label><label>Section<select name="section"><option>Primary</option><option>Secondary Boarding</option></select></label><label>Parent/Guardian<input name="guardian" required></label><label>Phone<input name="phone" required></label><label>Status<select name="status"><option>Active</option><option>Transferred</option><option>Graduated</option><option>Inactive</option></select></label><label class="full">Notes<textarea name="notes"></textarea></label><button class="portal-submit">Submit student record</button></form></article>
</section></div></main><footer class="report-footer"><strong>LynxCom Analytics</strong><span>Starter sample: online forms feeding structured backend records.</span></footer><script>document.querySelectorAll('[data-form]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-form]').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.form-panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');document.getElementById('form-'+btn.dataset.form).classList.add('active');history.replaceState(null,'','?form='+btn.dataset.form);});</script></body></html>